### ISSUE TITLE
Pyinstaller OCRmyPDF pikepdf packagenotfound error and failed to determine version

### ISSUE THREAD

**Issue by DerDoktorFaust** [ocrmypdf/OCRmyPDF#1033]
Hello. I am attempting to package my script in Pyinstaller. It uses OCRmyPDF, which I import. I make one call to it.

ocrmypdf.ocr(input_pdf, output_pdf, output_type="pdf", redo_ocr=True, language=languages, clean=True)

The issue is not the call to ocrmypdf but rather simply having imported the package and with it, pikepdf was installed.

If I remove ocrmypdf, my app works. It also works if I just run the script. The error only comes in when packaging with Pyinstaller.

The error I get is:

Traceback (most recent call last):
  File "pikepdf/__init__.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pikepdf/_version.py", line 11, in <module>
  File "importlib/metadata.py", line 551, in version
  File "importlib/metadata.py", line 524, in distribution
  File "importlib/metadata.py", line 187, in from_name
importlib.metadata.PackageNotFoundError: pikepdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ocrmypdf/__init__.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ocrmypdf/helpers.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pikepdf/__init__.py", line 18, in <module>
ImportError: Failed to determine version
[24094] Failed to execute script 'main' due to unhandled exception: Failed to determine version
[24094] Traceback:
Traceback (most recent call last):
  File "pikepdf/__init__.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pikepdf/_version.py", line 11, in <module>
  File "importlib/metadata.py", line 551, in version
  File "importlib/metadata.py", line 524, in distribution
  File "importlib/metadata.py", line 187, in from_name
importlib.metadata.PackageNotFoundError: pikepdf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ocrmypdf/__init__.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ocrmypdf/helpers.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pikepdf/__init__.py", line 18, in <module>
ImportError: Failed to determine version

I have tried hiddenimports on pyinstaller, I've done hooks that import all of pikepdf and ocrypdf stuff. I am losing my mind here. I've re-installed both ocrmypdf and pikepdf. I have no idea what to do from here.

Thank you for any help, it would really be appreciated!!!

**Comment by jbarlow83** [comment]
pikepdf and ocrmypdf both get their version numbers from setuptools-scm (that is, typically from their git tag). I suggest searching for instructions on using setuptools-scm with PyInstaller.

Also you will need to mark ocrmypdf's builtin_plugins folder as a hidden import. I remember that came up when someone tried PyInstaller before.

**Comment by digidigital** [comment]
I know this is more an issue of pyinstaller but since google leads you to this page when searching for the mentioned issue I think this is a good place to add some info ;)

Just as a hint on how to adjust the .spec-file so the pikepdf-import im pyinstaller does not cause the above mentioned "ImportError: Failed to determine version" + "unable to load pdfium" error:

```
# -*- mode: python ; coding: utf-8 -*-

##### add this line #####
from PyInstaller.utils.hooks import copy_metadata

datas = [ ('./lookups/*','./lookups'), #everything you want to have in datas in the Analysis step              
##### add correct path to pdfium.dll on your system  to get rid of unable to load pdfium error #####
             ('C:\\Users\\Username\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\pypdfium2\\pdfium.dll','.')              
             ]
##### add this to get rid of version error #####
datas += copy_metadata('pikepdf')
datas += copy_metadata('pypdfium2')

block_cipher = None

a = Analysis(['myScript.py'],
             pathex=[],
             binaries=[],

##### add "datas=datas" #####

             datas=datas,
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

----- rest of .spec file below this line was omitted --------
```

Not sure if an added import of pikepdf to your script is necessary as well.
