### ISSUE TITLE
[BUG] crash when trying to process a pdf

### ISSUE THREAD

**Issue by frrad** [ocrmypdf/OCRmyPDF#1052]
**Describe the bug**
I have a pdf which causes a crash.

**To Reproduce**

Just pulled a fresh docker image and ran:
```bash
docker run --rm -i jbarlow83/ocrmypdf -v1 - - <~/fastrak-2022-12-27.pdf >output.pdf
```

Here's the stack trace:
```
ocrmypdf 14.0.2.dev8+g14a60936.d20221215
Running: ['tesseract', '--version']
Found tesseract 5.2.0-80-g4906
Running: ['tesseract', '--version']
Running: ['gs', '--version']
Found gs 9.55.0
Running: ['gs', '--version']
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages in "/usr/share/tesseract-ocr/5/tessdata/" (7):
chi_sim
deu
eng
fra
osd
por
spa

reading file from standard input
os.symlink(/tmp/ocrmypdf.io.9dcgi0mu/stdin, /tmp/ocrmypdf.io.9dcgi0mu/origin.pdf)
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 934, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 711, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_concurrent.py", line 87, in __call__
    self._execute(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 668, in _pdf_pageinfo_sync
    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 748, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 794, in _gather_pageinfo
    for info in _process_content_streams(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 595, in _process_content_streams
    yield from _find_regular_images(container, contentsinfo)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 501, in _find_regular_images
    for pdfimage, xobj in _image_xobjects(container):
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _image_xobjects
    if '/Subtype' not in candidate:
TypeError: argument of type 'NoneType' is not iterable
```

**Example file**
[example.zip](https://github.com/ocrmypdf/OCRmyPDF/files/10328245/example.zip)

**System**

 - OS: Linux
 - OCRmyPDF Version: ``14.0.2.dev8+g14a60936.d20221215``
 - How did you install ocrmypdf? Docker

**Comment by frrad** [comment]
Fixed as of 14.0.2 https://github.com/ocrmypdf/OCRmyPDF/commit/f072e91120f2c596e3ed18c8e939a6d78a5917e5

Fixed by this commit https://github.com/ocrmypdf/OCRmyPDF/commit/90b2119ad36a7941f72dff8cabbb255ba7bfed70

Thank you!
