### ISSUE TITLE
[BUG] AttributeError: module 'PIL.Image' has no attribute 'Resampling' on running script

### ISSUE THREAD

**Issue by acarl123** [ocrmypdf/OCRmyPDF#1096]
**Describe the bug**
ocrmypdf crashes after fresh install

**To Reproduce**
`sudo apt install ocrmypdf` and then run `ocrmypdf` with any value or just on its own

**Expected behavior**
Running normally to either get a version output or convert a pdf

**Screenshots**
Entire stacktrace:
```andrewcarl:~/.local/lib/python3.10/site-packages$ ocrmypdf
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 33, in <module>
    sys.exit(load_entry_point('ocrmypdf==13.4.0+dfsg', 'console_scripts', 'ocrmypdf')())
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/__main__.py", line 41, in run
    _parser, options, plugin_manager = get_parser_options_plugins(args=args)
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 115, in get_parser_options_plugins
    plugin_manager = get_plugin_manager(pre_options.plugins)
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 104, in get_plugin_manager
    return OcrmypdfPluginManager(
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 45, in __init__
    self.setup_plugins()
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 73, in setup_plugins
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 18, in <module>
    from ocrmypdf.imageops import calculate_downsample, downsample_image
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/ocrmypdf/imageops.py", line 83, in <module>
    resample_mode: Image.Resampling = Image.Resampling.BICUBIC,
  File "/home/andrewcarl/.local/lib/python3.10/site-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

**System (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.10.6
 - OCRmyPDF version: crashes before I can see the version
 - Platform: x64 

**Installation**
I installed first from my distro's package manager, and then attempted to upgrade using pip. Both versions crashed

**Comment by JefPresotto** [comment]
Eu também estou com este problema. Alguem sabe do que se trata este erro?

**Comment by jbarlow83** [comment]
If you update to a newer version of Pillow (>9.1) the issue will be resolved. You may need to install ocrmypdf in a virtual environment to achieve this. The next release will include a fix to reinstate support for older versions.

**Comment by jbarlow83** [comment]
Fixed in v14.2.0

**Comment by rk041kumar** [comment]
I am facing the DecompressionBomb error
sometime image size extended to more than limit 
In OCRMYPDF PIP is troughing error and process is crashed.
anyone facing the issue same. Any solution
