### ISSUE TITLE
[Bug]: --remove-background it is showing an error 

### ISSUE THREAD

**Issue by wellingto198** [ocrmypdf/OCRmyPDF#1154]
### What were you trying to do?

An exception occurred while executing the pipeline                                                          _sync.py:455
Traceback (most recent call last):
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
391, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
279, in exec_concurrent
    executor(
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_concurrent.py",
line 85, in __call__
    self._execute(
  File
"C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\builtin_plugins\concurre
ncy.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449,
in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401,
in __get_result
    raise self._exception
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
196, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
130, in make_intermediate_images
    ocr_image = preprocess_out = preprocess(
                                 ^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
108, in preprocess
    image = preprocess_remove_background(image, page_context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_pipeline.py",
line 509, in preprocess_remove_background
    raise NotImplementedError("--remove-background is temporarily not implemented")
NotImplementedError: --remove-background is temporarily not implemented
PS C:\Windows\system32\OCRmyPDF>

I want to remove the background behind the text because after I go to translate the PDF, and if I don't remove the text from the image, the translation will stay on top and become unreadable 

### Where are you installing from?

Wndows package manager (chocolatey, etc.)

### What operating system are you working on?

Windows

### Relevant log output

```plain text
An exception occurred while executing the pipeline                                                          _sync.py:455
Traceback (most recent call last):
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
391, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
279, in exec_concurrent
    executor(
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_concurrent.py",
line 85, in __call__
    self._execute(
  File
"C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\builtin_plugins\concurre
ncy.py", line 141, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449,
in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401,
in __get_result
    raise self._exception
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
196, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
130, in make_intermediate_images
    ocr_image = preprocess_out = preprocess(
                                 ^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_sync.py", line
108, in preprocess
    image = preprocess_remove_background(image, page_context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\ocrmypdf\_pipeline.py",
line 509, in preprocess_remove_background
    raise NotImplementedError("--remove-background is temporarily not implemented")
NotImplementedError: --remove-background is temporarily not implemented
PS C:\Windows\system32\OCRmyPDF>
```

**Comment by jbarlow83** [comment]
Duplicate
