### ISSUE TITLE
[Bug]: Centos7 Install OCRmyPdf run command failed [Help]

### ISSUE THREAD

**Issue by huxinghai** [ocrmypdf/OCRmyPDF#1190]
### What were you trying to do?

run command error message

```bash
$ ocrmypdf
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/leptonica.py", line 61, in <module>
    """
ocrmypdf.exceptions.MissingDependencyError:
        ---------------------------------------------------------------------
        This error normally occurs when ocrmypdf can't find the Leptonica
        library, which is usually installed with Tesseract OCR. It could be that
        Tesseract is not installed properly, we can't find the installation
        on your system PATH environment variable.

        The library we are looking for is usually called:
            liblept-5.dll   (Windows)
            liblept*.dylib  (macOS)
            liblept*.so     (Linux/BSD)

        Please review our installation procedures to find a solution:
            https://ocrmypdf.readthedocs.io/en/latest/installation.html
        ---------------------------------------------------------------------
```

environment：

centos 7
python  3.6

```bash
$ ldconfig -v | grep lept

/mnt/src/leptonica/src/.libs:
	libleptonica.so.6 -> libleptonica.so.6.0.0
	libleptonica.so.6 -> libleptonica.so.6.0.0

$ ll /usr/local/lib | grep lept
-rw-r--r-- 1 root root   5288154 11月 11 22:56 libleptonica.a
-rwxr-xr-x 1 root root       989 11月 11 22:56 libleptonica.la
lrwxrwxrwx 1 root root        21 11月 11 22:56 libleptonica.so -> libleptonica.so.6.0.0
lrwxrwxrwx 1 root root        21 11月 11 22:56 libleptonica.so.6 -> libleptonica.so.6.0.0
-rwxr-xr-x 1 root root   3227456 11月 11 22:56 libleptonica.so.6.0.0

$ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library("lept")
>>>

```

The error message looks like a system configuration issue, but I've tried configuring a lot of things and it still doesn't work.

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, leptonica, pdfa, pdfinfo
  File "/usr/local/lib/python3.6/site-packages/ocrmypdf/leptonica.py", line 61, in <module>
    """
ocrmypdf.exceptions.MissingDependencyError:
        ---------------------------------------------------------------------
        This error normally occurs when ocrmypdf can't find the Leptonica
        library, which is usually installed with Tesseract OCR. It could be that
        Tesseract is not installed properly, we can't find the installation
        on your system PATH environment variable.

        The library we are looking for is usually called:
            liblept-5.dll   (Windows)
            liblept*.dylib  (macOS)
            liblept*.so     (Linux/BSD)

        Please review our installation procedures to find a solution:
            https://ocrmypdf.readthedocs.io/en/latest/installation.html
        ---------------------------------------------------------------------
```

**Comment by jbarlow83** [comment]
Sorry, that's way too old to support.

**Comment by huxinghai** [comment]
> Sorry, that's way too old to support.

Is the Python version too old?

**Comment by jbarlow83** [comment]
Every piece of software involved is too old

**Comment by huxinghai** [comment]
> Every piece of software involved is too old

Thank you reply
