### ISSUE TITLE
[Bug]: ImportError: cannot import name 'PDFTextSeq' from 'pdfminer.pdfdevice'

### ISSUE THREAD

**Issue by MimoGraphix** [ocrmypdf/OCRmyPDF#1196]
### What were you trying to do?

Latest version tries to import PDFTextSeq from package pdfminer.

This is list of installed pip packages:
```
$ pip list
Package                   Version
------------------------- ------------
argcomplete               1.10.3
attrs                     23.1.0
beautifulsoup4            4.8.2
blinker                   1.7.0
certifi                   2023.11.17
cffi                      1.16.0
chardet                   3.0.4
charset-normalizer        3.3.2
click                     8.1.7
compressed-rtf            1.0.6
contourpy                 1.2.0
cryptography              41.0.7
cycler                    0.12.1
Deprecated                1.2.14
deprecation               2.1.0
distro                    1.8.0
dnspython                 2.4.2
docx2txt                  0.8
ebcdic                    1.1.1
EbookLib                  0.16
extract-msg               0.28.7
Flask                     3.0.0
fonttools                 4.45.1
idna                      3.6
imageio                   2.33.0
IMAPClient                2.1.0
img2pdf                   0.5.1
itsdangerous              2.1.2
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.20.0
jsonschema-specifications 2023.11.1
kiwisolver                1.4.5
lazy_loader               0.3
lxml                      4.9.3
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.2
mdurl                     0.1.2
mongo-queue-service       0.2.0
networkx                  3.2.1
numpy                     1.26.2
ocrmypdf                  15.4.3
olefile                   0.46
opencv-contrib-python     4.8.1.78
opencv-python             4.8.1.78
packaging                 23.2
pandas                    2.1.3
pdf2image                 1.16.3
pdfminer.six              20191110
pikepdf                   8.7.1
Pillow                    10.1.0
pip                       23.1.2
pluggy                    1.3.0
pocketsphinx              0.1.15
pycparser                 2.21
pycryptodome              3.19.0
Pygments                  2.17.2
pymongo                   4.6.0
PyMySQL                   1.1.0
pyparsing                 3.1.1
PyPDF2                    3.0.1
pypng                     0.20220715.0
python-dateutil           2.8.2
python-pptx               0.6.23
pytz                      2023.3.post1
qrtools                   0.0.2
redis                     5.0.1
referencing               0.31.0
reportlab                 4.0.7
requests                  2.31.0
rich                      13.7.0
rpds-py                   0.13.1
scikit-image              0.22.0
scikit-learn              1.3.2
scipy                     1.11.4
setuptools                65.5.1
six                       1.12.0
sortedcontainers          2.4.0
soupsieve                 2.5
SpeechRecognition         3.8.1
tabula-py                 2.9.0
textract                  1.6.5
threadpoolctl             3.2.0
tifffile                  2023.9.26
tzdata                    2023.3
tzlocal                   5.2
urllib3                   2.1.0
Werkzeug                  3.0.1
wheel                     0.40.0
wrapt                     1.16.0
xlrd                      1.2.0
XlsxWriter                3.1.9
zbar-py                   1.0.4
```

### Where are you installing from?

PyPI (pip, poetry, pipx, etc.), Linux package manager (apt, dnf, etc.)

### What operating system are you working on?

Linux

### Relevant log output

```plain text
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 5, in <module>
    from ocrmypdf.__main__ import run
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, pdfa, pdfinfo
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/__init__.py", line 9, in <module>
    from ocrmypdf.pdfinfo.info import Colorspace, Encoding, PageInfo, PdfInfo
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/info.py", line 44, in <module>
    from ocrmypdf.pdfinfo.layout import LTStateAwareChar, get_page_analysis, get_text_boxes
  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/pdfinfo/layout.py", line 23, in <module>
    from pdfminer.pdfdevice import PDFTextSeq
ImportError: cannot import name 'PDFTextSeq' from 'pdfminer.pdfdevice' (/usr/local/lib/python3.11/site-packages/pdfminer/pdfdevice.py)
```

**Comment by jbarlow83** [comment]
The installed pdfminer.six is too old. Please use a newer version.
