### ISSUE TITLE
[Bug]: Unknown tesseract error, returns non-zero

### ISSUE THREAD

**Issue by nepomuc** [ocrmypdf/OCRmyPDF#1241]
### Describe the bug

Hey guys,
I'm using ocrmypdf in paperless and get a tesseract error for one specific file I unfortunately can't share with you.
To be honest I don't even know what the actual error is. So maybe you could help with finding this out first?
I already tried to figure this out but to me the error log doesn't really tell anything about the real cause of the error.
I already increased tesseract-timeout to 360, so it's probably not a simple timeout issue or is it?

### Steps to reproduce

```plain text
Making paperless trying to consume and run OCRmyPDF on it.
```

### Files

Unfortunately I can't share the file with you. But maybe it's a useful information that a lot of very similar documents (Same size, resolution, scanner, PDF-generating software, ...) have been able to be processed without any errors.

### How did you download and install the software?

Docker container

### OCRmyPDF version

15.4.4

### Relevant log output

```plain text
Error log from paperless:


[2024-01-28 12:40:57,004] [ERROR] [paperless.consumer] Error occurred while consuming document Beschaffungsprozesse-04.pdf: SubprocessOutputError: . See logs for more information.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 201, in get_deskew

    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/subprocess/__init__.py", line 63, in run

    proc = subprocess_run(args, env=env, check=check, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['tesseract', '-l', 'deu+eng', '--psm', '2', '/tmp/ocrmypdf.io.hwtykefd/000007_rasterize.png', 'stdout']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 353, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 375, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 225, in run_pipeline

    return _run_pipeline(options, plugin_manager)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 192, in _run_pipeline

    optimize_messages = exec_concurrent(context, executor)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 119, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_concurrent.py", line 74, in __call__

    self._execute(

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute

    result = future.result()

             ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result

    return self.__get_result()

           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 79, in _exec_page_sync

    ocr_image_out, pdf_page_from_image_out, orientation_correction = process_page(

                                                                     ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 391, in process_page

    ocr_image, preprocess_out = make_intermediate_images(

                                ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 344, in make_intermediate_images

    preprocess_out = preprocess(

                     ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/_common.py", line 314, in preprocess

    image = preprocess_deskew(image, page_context)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipeline.py", line 569, in preprocess_deskew

    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 239, in get_deskew

    return tesseract.get_deskew(

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/tesseract.py", line 212, in get_deskew

    raise SubprocessOutputError() from e

ocrmypdf.exceptions.SubprocessOutputError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 516, in try_consume_file

    document_parser.parse(self.working_copy, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 376, in parse

    raise ParseError(

documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.
```
```

**Comment by jbarlow83** [comment]
My guess is that you need to install `tesseract-ocr-osd`, Tesseract's data files for orientation and script detection. Furthermore, paperless's error handling seems to be raising an exception of its own instead of logging the message from ocrmypdf.

Might also want to look into paperless-ngx, which I think has more active maintenance currently.
