### ISSUE TITLE
[Bug] SubprocessOutputError

### ISSUE THREAD

**Issue by user1823** [ocrmypdf/OCRmyPDF#1281]
### Describe the bug

I tried to OCR a PDF file. However, the OCR couldn't be completed.

### Steps to reproduce

```plain text
1. Run ocrmypdf -v1 --max-image-mpixels 1000 --output-type pdf test.pdf ocr.pdf
2. See error message
```

### Files

[test.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14639223/test.pdf)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

ocrmypdf 16.1.1

### Relevant log output

```plain text
C:\Users\User\Desktop\New folder (4)>ocrmypdf -v1 --max-image-mpixels 1000 --output-type pdf test.pdf ocr.pdf
ocrmypdf 16.1.1                                                                                           __main__.py:59
Running: ['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '--version']                                __init__.py:133
Found tesseract 5.3.3.20231005                                                                           __init__.py:342
Running: ['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '--version']                                __init__.py:133
Running: ['C:\\Program Files\\gs\\gs10.02.1\\bin\\gswin64c.EXE', '--version']                            __init__.py:133
Found gs 10.2.1                                                                                          __init__.py:342
Running: ['C:\\Program Files\\gs\\gs10.02.1\\bin\\gswin64c.EXE', '--version']                            __init__.py:133
Running: ['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '--list-langs']                             __init__.py:133
stdout/stderr = List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (2):            __init__.py:73
eng
osd

No language specified; assuming --language eng                                                         _validation.py:61
pikepdf mmap enabled                                                                                      helpers.py:326
Gathering info with 1 thread workers                                                                         info.py:772
pikepdf mmap enabled                                                                                      helpers.py:326
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Using Tesseract OpenMP thread limit 3                                                               tesseract_ocr.py:183
pikepdf mmap enabled                                                                                      helpers.py:326
    1 Rasterize with png16m, rotation 0                                                                 _pipeline.py:528
    1 Running: ['C:\\Program Files\\gs\\gs10.02.1\\bin\\gswin64c.EXE', '-dQUIET', '-dSAFER', '-dBATCH',  __init__.py:133
'-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1',
'-r2471.578862x2471.578862', '-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr',
'-dAutoRotatePages=/None', '-f',
'C:\\Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.fhgq3ci2\\origin.pdf']
    1 Rotating output by 0                                                                            ghostscript.py:149
    1 resolution (2471.5724, 2471.5724)                                                                 _pipeline.py:607
    1 Running: ['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '-l', 'eng',                          __init__.py:133
'C:\\Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.fhgq3ci2\\000001_ocr.png',
'C:\\Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.fhgq3ci2\\000001_ocr_hocr', 'hocr', 'txt']
    1  Error in pixCreateHeader: requested w = 21008, h = 28145, d = 32                                 tesseract.py:252
    1  Error in pixCreateHeader: requested bytes >= 2^31                                                tesseract.py:252
    1  Error in pixCreateNoInit: pixd not made                                                          tesseract.py:252
    1  Error in pixCreate: pixd not made                                                                tesseract.py:252
    1  Error in pixReadStreamPng: pix not made                                                          tesseract.py:252
    1  Error in pixReadStream: png: no pix returned                                                     tesseract.py:252
    1  Error in pixRead: pix not read                                                                   tesseract.py:252
    1  Error during processing.                                                                         tesseract.py:252
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/1 -:--:--
ExitCodeException                                                                                         _common.py:259
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_exec\tesseract.py", line 312, in
generate_hocr
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\subprocess\__init__.py", line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Tesseract-OCR\\tesseract.EXE', '-l', 'eng',
'C:\\Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.fhgq3ci2\\000001_ocr.png',
'C:\\Users\\User\\AppData\\Local\\Temp\\ocrmypdf.io.fhgq3ci2\\000001_ocr_hocr', 'hocr', 'txt']' returned
non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipelines\_common.py", line 249, in
cli_exception_handler
    return fn(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipelines\ocr.py", line 191, in
_run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipelines\ocr.py", line 118, in
exec_concurrent
    executor(
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_concurrent.py", line 78, in __call__
    self._execute(
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\builtin_plugins\concurrency.py", line 144,
in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipelines\ocr.py", line 82, in
_exec_page_sync
    ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipelines\ocr.py", line 63, in
_image_to_ocr_text
    hocr_out, text_out = ocr_engine_hocr(ocr_image_out, page_context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_pipeline.py", line 654, in ocr_engine_hocr
    ocr_engine.generate_hocr(
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\builtin_plugins\tesseract_ocr.py", line
252, in generate_hocr
    tesseract.generate_hocr(
  File "C:\Program Files\Python312\Lib\site-packages\ocrmypdf\_exec\tesseract.py", line 326, in
generate_hocr
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
```

**Comment by jbarlow83** [comment]
`ocrmypdf -v1 --max-image-mpixels 1000 --tesseract-downsample-large-images --output-type pdf test.pdf ocr.pdf` will work in recent versions (v16+). In some future release that argument will be enabled by default since there's no reason not to.

A further complication in this file it that uses a lot of stencil masks, some with odd proportions, and ocrmypdf is very cautious about degrading image quality so it picks a very large output image size as a way of accurately accounting for these stencil masks. This is a tricky issue since there are legitimately use cases of very high resolution files, when working with scanned film for example.

You can add `--tesseract-downsample-above 3000` for example, and OCR will complete more quickly.

**Comment by user1823** [comment]
> You can add --tesseract-downsample-above 3000 for example, and OCR will complete more quickly.

Thanks for the suggestion.

**Comment by Firestar-Reimu** [comment]
`ocrmypdf -l chi_sim+eng+osd+equ --jobs 8 --output-type pdf --force-ocr input.pdf output.pdf` also `SubprocessOutputError`, error with and without the `--force-ocr`, I want to know if this is because poor OCR

<details>

```bash
$ ocrmypdf -l chi_sim+eng+osd+equ --jobs 8 --output-type pdf --force-ocr input.pdf output.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 664/664 0:00:00
Start processing 8 pages concurrently                                                                                             ocr.py:96
    2  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   18  Empty page!!                                                                                                        tesseract.py:259
   18  Empty page!!                                                                                                        tesseract.py:259
   11  no best words!!                                                                                                     tesseract.py:259
   23  no best words!!                                                                                                     tesseract.py:259
   23  no best words!!                                                                                                     tesseract.py:259
   20  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   24  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   49  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   54  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   54  no best words!!                                                                                                     tesseract.py:259
   54  no best words!!                                                                                                     tesseract.py:259
   54  no best words!!                                                                                                     tesseract.py:259
   54  no best words!!                                                                                                     tesseract.py:259
   51  no best words!!                                                                                                     tesseract.py:259
   51  no best words!!                                                                                                     tesseract.py:259
   51  no best words!!                                                                                                     tesseract.py:259
   56  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   58  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   57  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   59  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   64  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   64  no best words!!                                                                                                     tesseract.py:259
   64  no best words!!                                                                                                     tesseract.py:259
   64  no best words!!                                                                                                     tesseract.py:259
   61  no best words!!                                                                                                     tesseract.py:259
   66  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   69  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   69  no best words!!                                                                                                     tesseract.py:259
   69  no best words!!                                                                                                     tesseract.py:259
   69  no best words!!                                                                                                     tesseract.py:259
   69  no best words!!                                                                                                     tesseract.py:259
   69  no best words!!                                                                                                     tesseract.py:259
   70  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   68  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   80  Empty page!!                                                                                                        tesseract.py:259
   80  Empty page!!                                                                                                        tesseract.py:259
   85  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   85  no best words!!                                                                                                     tesseract.py:259
   84  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   87  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   88  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   89  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   89  no best words!!                                                                                                     tesseract.py:259
   89  no best words!!                                                                                                     tesseract.py:259
   89  no best words!!                                                                                                     tesseract.py:259
   89  no best words!!                                                                                                     tesseract.py:259
   90  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
   90  no best words!!                                                                                                     tesseract.py:259
   97  no best words!!                                                                                                     tesseract.py:259
   97  no best words!!                                                                                                     tesseract.py:259
   98  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  107  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  112  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  117  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  119  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  118  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  115  no best words!!                                                                                                     tesseract.py:259
  120  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  120  no best words!!                                                                                                     tesseract.py:259
  122  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  122  no best words!!                                                                                                     tesseract.py:259
  122  no best words!!                                                                                                     tesseract.py:259
  122  no best words!!                                                                                                     tesseract.py:259
  122  no best words!!                                                                                                     tesseract.py:259
  123  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  126  no best words!!                                                                                                     tesseract.py:259
  126  no best words!!                                                                                                     tesseract.py:259
  126  no best words!!                                                                                                     tesseract.py:259
  126  no best words!!                                                                                                     tesseract.py:259
  126  no best words!!                                                                                                     tesseract.py:259
  126  no best words!!                                                                                                     tesseract.py:259
  132  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  132  no best words!!                                                                                                     tesseract.py:259
  132  no best words!!                                                                                                     tesseract.py:259
  132  no best words!!                                                                                                     tesseract.py:259
  135  no best words!!                                                                                                     tesseract.py:259
  137  no best words!!                                                                                                     tesseract.py:259
  138  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  140  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  147  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  150  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  156  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  151  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  154  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  164  no best words!!                                                                                                     tesseract.py:259
  164  no best words!!                                                                                                     tesseract.py:259
  164  no best words!!                                                                                                     tesseract.py:259
  164  no best words!!                                                                                                     tesseract.py:259
  164  no best words!!                                                                                                     tesseract.py:259
  164  no best words!!                                                                                                     tesseract.py:259
  163  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  162  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  168  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  173  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  178  Empty page!!                                                                                                        tesseract.py:259
  178  Empty page!!                                                                                                        tesseract.py:259
  174  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  174  no best words!!                                                                                                     tesseract.py:259
  174  no best words!!                                                                                                     tesseract.py:259
  174  no best words!!                                                                                                     tesseract.py:259
  169  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  181  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  182  no best words!!                                                                                                     tesseract.py:259
  175  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  175  no best words!!                                                                                                     tesseract.py:259
  184  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  184  no best words!!                                                                                                     tesseract.py:259
  187  no best words!!                                                                                                     tesseract.py:259
  189  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  191  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  194  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  195  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  205  no best words!!                                                                                                     tesseract.py:259
  205  no best words!!                                                                                                     tesseract.py:259
  209  no best words!!                                                                                                     tesseract.py:259
  211  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  218  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  218  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  217  no best words!!                                                                                                     tesseract.py:259
  215  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  220  no best words!!                                                                                                     tesseract.py:259
  220  no best words!!                                                                                                     tesseract.py:259
  221  no best words!!                                                                                                     tesseract.py:259
  223  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  222  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  227  no best words!!                                                                                                     tesseract.py:259
  227  no best words!!                                                                                                     tesseract.py:259
  227  no best words!!                                                                                                     tesseract.py:259
  224  no best words!!                                                                                                     tesseract.py:259
  224  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  226  no best words!!                                                                                                     tesseract.py:259
  229  no best words!!                                                                                                     tesseract.py:259
  229  no best words!!                                                                                                     tesseract.py:259
  229  no best words!!                                                                                                     tesseract.py:259
  229  no best words!!                                                                                                     tesseract.py:259
  228  no best words!!                                                                                                     tesseract.py:259
  228  no best words!!                                                                                                     tesseract.py:259
  228  no best words!!                                                                                                     tesseract.py:259
  231  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  225  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  225  no best words!!                                                                                                     tesseract.py:259
  225  no best words!!                                                                                                     tesseract.py:259
  225  no best words!!                                                                                                     tesseract.py:259
  233  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  232  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  232  no best words!!                                                                                                     tesseract.py:259
  234  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  235  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  235  no best words!!                                                                                                     tesseract.py:259
  235  no best words!!                                                                                                     tesseract.py:259
  236  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  239  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  238  no best words!!                                                                                                     tesseract.py:259
  238  no best words!!                                                                                                     tesseract.py:259
  246  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  244  no best words!!                                                                                                     tesseract.py:259
  244  no best words!!                                                                                                     tesseract.py:259
  245  no best words!!                                                                                                     tesseract.py:259
  245  no best words!!                                                                                                     tesseract.py:259
  245  no best words!!                                                                                                     tesseract.py:259
  247  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  261  no best words!!                                                                                                     tesseract.py:259
  261  no best words!!                                                                                                     tesseract.py:259
  262  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  264  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  263  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  266  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  266  no best words!!                                                                                                     tesseract.py:259
  269  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  265  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  265  no best words!!                                                                                                     tesseract.py:259
  265  no best words!!                                                                                                     tesseract.py:259
  265  no best words!!                                                                                                     tesseract.py:259
  265  no best words!!                                                                                                     tesseract.py:259
  268  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  270  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  272  no best words!!                                                                                                     tesseract.py:259
  272  no best words!!                                                                                                     tesseract.py:259
  272  no best words!!                                                                                                     tesseract.py:259
  274  no best words!!                                                                                                     tesseract.py:259
  274  no best words!!                                                                                                     tesseract.py:259
  278  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  276  no best words!!                                                                                                     tesseract.py:259
  276  no best words!!                                                                                                     tesseract.py:259
  284  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  284  no best words!!                                                                                                     tesseract.py:259
  284  no best words!!                                                                                                     tesseract.py:259
  289  no best words!!                                                                                                     tesseract.py:259
  289  no best words!!                                                                                                     tesseract.py:259
  286  no best words!!                                                                                                     tesseract.py:259
  285  no best words!!                                                                                                     tesseract.py:259
  285  no best words!!                                                                                                     tesseract.py:259
  287  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  304  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  304  no best words!!                                                                                                     tesseract.py:259
  304  no best words!!                                                                                                     tesseract.py:259
  300  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  305  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  305  no best words!!                                                                                                     tesseract.py:259
  307  no best words!!                                                                                                     tesseract.py:259
  307  no best words!!                                                                                                     tesseract.py:259
  307  no best words!!                                                                                                     tesseract.py:259
  307  no best words!!                                                                                                     tesseract.py:259
  307  no best words!!                                                                                                     tesseract.py:259
  302  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  310  no best words!!                                                                                                     tesseract.py:259
  310  no best words!!                                                                                                     tesseract.py:259
  310  no best words!!                                                                                                     tesseract.py:259
  310  no best words!!                                                                                                     tesseract.py:259
  317  no best words!!                                                                                                     tesseract.py:259
  317  no best words!!                                                                                                     tesseract.py:259
  317  no best words!!                                                                                                     tesseract.py:259
  317  no best words!!                                                                                                     tesseract.py:259
  317  no best words!!                                                                                                     tesseract.py:259
  319  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  314  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  326  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  324  no best words!!                                                                                                     tesseract.py:259
  324  no best words!!                                                                                                     tesseract.py:259
  329  no best words!!                                                                                                     tesseract.py:259
  337  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  339  no best words!!                                                                                                     tesseract.py:259
  339  no best words!!                                                                                                     tesseract.py:259
  339  no best words!!                                                                                                     tesseract.py:259
  340  no best words!!                                                                                                     tesseract.py:259
  340  no best words!!                                                                                                     tesseract.py:259
  341  no best words!!                                                                                                     tesseract.py:259
  342  no best words!!                                                                                                     tesseract.py:259
  342  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  343  no best words!!                                                                                                     tesseract.py:259
  352  Empty page!!                                                                                                        tesseract.py:259
  352  Empty page!!                                                                                                        tesseract.py:259
  355  no best words!!                                                                                                     tesseract.py:259
  354  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  354  no best words!!                                                                                                     tesseract.py:259
  344  no best words!!                                                                                                     tesseract.py:259
  344  no best words!!                                                                                                     tesseract.py:259
  357  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  356  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  358  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  359  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  360  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  360  no best words!!                                                                                                     tesseract.py:259
  362  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  361  no best words!!                                                                                                     tesseract.py:259
  361  no best words!!                                                                                                     tesseract.py:259
  361  no best words!!                                                                                                     tesseract.py:259
  372  no best words!!                                                                                                     tesseract.py:259
  372  no best words!!                                                                                                     tesseract.py:259
  374  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  373  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  378  no best words!!                                                                                                     tesseract.py:259
  379  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  380  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  387  no best words!!                                                                                                     tesseract.py:259
  385  no best words!!                                                                                                     tesseract.py:259
  385  no best words!!                                                                                                     tesseract.py:259
  393  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  390  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  394  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  394  no best words!!                                                                                                     tesseract.py:259
  395  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  405  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  406  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  401  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  404  no best words!!                                                                                                     tesseract.py:259
  407  lots of diacritics - possibly poor OCR                                                                              tesseract.py:241
  416  no best words!!                                                                                                     tesseract.py:259
  419  no best words!!                                                                                                     tesseract.py:259
  418  no best words!!                                                                                                     tesseract.py:259
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  62% 414/664 0:08:52
SubprocessOutputError
```

</details>

**Comment by jbarlow83** [comment]
@Firestar-Reimu open a new issue and include your test file (or preferably, one page of it)
