### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Firestar-Reimu** [ocrmypdf/OCRmyPDF#1318]
### Describe the bug

```bash
ocrmypdf -l chi_sim+eng+osd+equ --jobs 8 --force-ocr "引力和宇宙学——广义相对论的原理和应用 (斯蒂芬·温伯格).pdf"  output.pdf

Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 664/664 0:00:00
Start processing 8 pages concurrently                                                                ocr.py:96
    2  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   18  Empty page!!                                                                           tesseract.py:259
   18  Empty page!!                                                                           tesseract.py:259
   11  no best words!!                                                                        tesseract.py:259
   23  no best words!!                                                                        tesseract.py:259
   23  no best words!!                                                                        tesseract.py:259
   20  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   24  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   49  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   54  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   54  no best words!!                                                                        tesseract.py:259
   54  no best words!!                                                                        tesseract.py:259
   54  no best words!!                                                                        tesseract.py:259
   54  no best words!!                                                                        tesseract.py:259
   51  no best words!!                                                                        tesseract.py:259
   51  no best words!!                                                                        tesseract.py:259
   51  no best words!!                                                                        tesseract.py:259
   56  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   58  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   57  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   59  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   61  no best words!!                                                                        tesseract.py:259
   64  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   64  no best words!!                                                                        tesseract.py:259
   64  no best words!!                                                                        tesseract.py:259
   64  no best words!!                                                                        tesseract.py:259
   66  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   69  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   69  no best words!!                                                                        tesseract.py:259
   69  no best words!!                                                                        tesseract.py:259
   69  no best words!!                                                                        tesseract.py:259
   69  no best words!!                                                                        tesseract.py:259
   69  no best words!!                                                                        tesseract.py:259
   68  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   70  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   80  Empty page!!                                                                           tesseract.py:259
   80  Empty page!!                                                                           tesseract.py:259
   85  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   85  no best words!!                                                                        tesseract.py:259
   84  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   88  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   87  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   89  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   89  no best words!!                                                                        tesseract.py:259
   89  no best words!!                                                                        tesseract.py:259
   89  no best words!!                                                                        tesseract.py:259
   89  no best words!!                                                                        tesseract.py:259
   90  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
   90  no best words!!                                                                        tesseract.py:259
   97  no best words!!                                                                        tesseract.py:259
   97  no best words!!                                                                        tesseract.py:259
   98  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  107  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  112  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  117  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  119  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  118  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  115  no best words!!                                                                        tesseract.py:259
  120  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  120  no best words!!                                                                        tesseract.py:259
  122  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  122  no best words!!                                                                        tesseract.py:259
  122  no best words!!                                                                        tesseract.py:259
  122  no best words!!                                                                        tesseract.py:259
  122  no best words!!                                                                        tesseract.py:259
  123  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  126  no best words!!                                                                        tesseract.py:259
  126  no best words!!                                                                        tesseract.py:259
  126  no best words!!                                                                        tesseract.py:259
  126  no best words!!                                                                        tesseract.py:259
  126  no best words!!                                                                        tesseract.py:259
  126  no best words!!                                                                        tesseract.py:259
  132  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  132  no best words!!                                                                        tesseract.py:259
  132  no best words!!                                                                        tesseract.py:259
  132  no best words!!                                                                        tesseract.py:259
  135  no best words!!                                                                        tesseract.py:259
  137  no best words!!                                                                        tesseract.py:259
  138  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  140  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  147  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  150  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  156  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  151  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  154  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  164  no best words!!                                                                        tesseract.py:259
  164  no best words!!                                                                        tesseract.py:259
  164  no best words!!                                                                        tesseract.py:259
  164  no best words!!                                                                        tesseract.py:259
  164  no best words!!                                                                        tesseract.py:259
  164  no best words!!                                                                        tesseract.py:259
  163  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  162  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  168  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  173  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  178  Empty page!!                                                                           tesseract.py:259
  178  Empty page!!                                                                           tesseract.py:259
  174  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  174  no best words!!                                                                        tesseract.py:259
  174  no best words!!                                                                        tesseract.py:259
  174  no best words!!                                                                        tesseract.py:259
  169  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  181  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  175  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  175  no best words!!                                                                        tesseract.py:259
  182  no best words!!                                                                        tesseract.py:259
  184  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  184  no best words!!                                                                        tesseract.py:259
  187  no best words!!                                                                        tesseract.py:259
  189  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  191  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  194  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  195  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  205  no best words!!                                                                        tesseract.py:259
  205  no best words!!                                                                        tesseract.py:259
  209  no best words!!                                                                        tesseract.py:259
  211  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  218  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  218  no best words!!                                                                        tesseract.py:259
  215  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  217  no best words!!                                                                        tesseract.py:259
  220  no best words!!                                                                        tesseract.py:259
  220  no best words!!                                                                        tesseract.py:259
  221  no best words!!                                                                        tesseract.py:259
  223  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  222  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  224  no best words!!                                                                        tesseract.py:259
  224  no best words!!                                                                        tesseract.py:259
  227  no best words!!                                                                        tesseract.py:259
  227  no best words!!                                                                        tesseract.py:259
  227  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  226  no best words!!                                                                        tesseract.py:259
  229  no best words!!                                                                        tesseract.py:259
  229  no best words!!                                                                        tesseract.py:259
  229  no best words!!                                                                        tesseract.py:259
  229  no best words!!                                                                        tesseract.py:259
  228  no best words!!                                                                        tesseract.py:259
  228  no best words!!                                                                        tesseract.py:259
  228  no best words!!                                                                        tesseract.py:259
  231  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  225  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  225  no best words!!                                                                        tesseract.py:259
  225  no best words!!                                                                        tesseract.py:259
  225  no best words!!                                                                        tesseract.py:259
  233  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  234  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  232  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  232  no best words!!                                                                        tesseract.py:259
  235  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  235  no best words!!                                                                        tesseract.py:259
  235  no best words!!                                                                        tesseract.py:259
  236  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  239  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  238  no best words!!                                                                        tesseract.py:259
  238  no best words!!                                                                        tesseract.py:259
  246  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  244  no best words!!                                                                        tesseract.py:259
  244  no best words!!                                                                        tesseract.py:259
  245  no best words!!                                                                        tesseract.py:259
  245  no best words!!                                                                        tesseract.py:259
  245  no best words!!                                                                        tesseract.py:259
  247  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  261  no best words!!                                                                        tesseract.py:259
  261  no best words!!                                                                        tesseract.py:259
  264  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  262  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  263  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  266  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  266  no best words!!                                                                        tesseract.py:259
  269  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  265  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  265  no best words!!                                                                        tesseract.py:259
  265  no best words!!                                                                        tesseract.py:259
  265  no best words!!                                                                        tesseract.py:259
  265  no best words!!                                                                        tesseract.py:259
  268  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  270  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  272  no best words!!                                                                        tesseract.py:259
  272  no best words!!                                                                        tesseract.py:259
  272  no best words!!                                                                        tesseract.py:259
  274  no best words!!                                                                        tesseract.py:259
  274  no best words!!                                                                        tesseract.py:259
  278  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  276  no best words!!                                                                        tesseract.py:259
  276  no best words!!                                                                        tesseract.py:259
  284  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  284  no best words!!                                                                        tesseract.py:259
  284  no best words!!                                                                        tesseract.py:259
  285  no best words!!                                                                        tesseract.py:259
  285  no best words!!                                                                        tesseract.py:259
  289  no best words!!                                                                        tesseract.py:259
  289  no best words!!                                                                        tesseract.py:259
  286  no best words!!                                                                        tesseract.py:259
  287  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  304  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  304  no best words!!                                                                        tesseract.py:259
  304  no best words!!                                                                        tesseract.py:259
  300  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  305  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  305  no best words!!                                                                        tesseract.py:259
  307  no best words!!                                                                        tesseract.py:259
  307  no best words!!                                                                        tesseract.py:259
  307  no best words!!                                                                        tesseract.py:259
  307  no best words!!                                                                        tesseract.py:259
  307  no best words!!                                                                        tesseract.py:259
  302  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  310  no best words!!                                                                        tesseract.py:259
  310  no best words!!                                                                        tesseract.py:259
  310  no best words!!                                                                        tesseract.py:259
  310  no best words!!                                                                        tesseract.py:259
  317  no best words!!                                                                        tesseract.py:259
  317  no best words!!                                                                        tesseract.py:259
  317  no best words!!                                                                        tesseract.py:259
  317  no best words!!                                                                        tesseract.py:259
  317  no best words!!                                                                        tesseract.py:259
  319  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  314  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  326  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  324  no best words!!                                                                        tesseract.py:259
  324  no best words!!                                                                        tesseract.py:259
  329  no best words!!                                                                        tesseract.py:259
  337  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  339  no best words!!                                                                        tesseract.py:259
  339  no best words!!                                                                        tesseract.py:259
  339  no best words!!                                                                        tesseract.py:259
  340  no best words!!                                                                        tesseract.py:259
  340  no best words!!                                                                        tesseract.py:259
  341  no best words!!                                                                        tesseract.py:259
  342  no best words!!                                                                        tesseract.py:259
  342  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  343  no best words!!                                                                        tesseract.py:259
  352  Empty page!!                                                                           tesseract.py:259
  352  Empty page!!                                                                           tesseract.py:259
  355  no best words!!                                                                        tesseract.py:259
  354  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  354  no best words!!                                                                        tesseract.py:259
  344  no best words!!                                                                        tesseract.py:259
  344  no best words!!                                                                        tesseract.py:259
  357  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  356  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  358  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  360  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  360  no best words!!                                                                        tesseract.py:259
  359  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  362  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  361  no best words!!                                                                        tesseract.py:259
  361  no best words!!                                                                        tesseract.py:259
  361  no best words!!                                                                        tesseract.py:259
  372  no best words!!                                                                        tesseract.py:259
  372  no best words!!                                                                        tesseract.py:259
  374  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  373  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  379  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  378  no best words!!                                                                        tesseract.py:259
  380  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  387  no best words!!                                                                        tesseract.py:259
  385  no best words!!                                                                        tesseract.py:259
  385  no best words!!                                                                        tesseract.py:259
  390  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  393  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  394  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  394  no best words!!                                                                        tesseract.py:259
  395  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  405  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  401  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  406  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  404  no best words!!                                                                        tesseract.py:259
  407  lots of diacritics - possibly poor OCR                                                 tesseract.py:241
  416  no best words!!                                                                        tesseract.py:259
  418  no best words!!                                                                        tesseract.py:259
  419  no best words!!                                                                        tesseract.py:259
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  62% 414/664 0:15:02
SubprocessOutputError
```

### Steps to reproduce

```plain text
Also, I tried `--output-type pdf`, or do not use `--jobs 8` and it still failed.
```

### Files

https://cowtransfer.com/s/34bea722ef674c (expires in 30 days)

### OCRmyPDF version

16.3.1

### Relevant log output

```plain text
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  62% 414/664 0:08:06
ExitCodeException                                                                               _common.py:259
Traceback (most recent call last):                                                                            
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py",                  
line 313, in generate_hocr                                                                                    
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)                          
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
  File                                                                                                        
"/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/subprocess/__init__.py", line                
62, in run                                                                                                    
    proc = subprocess_run(args, env=env, check=check, **kwargs)                                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               
  File "/home/firestar/.miniconda/lib/python3.12/subprocess.py", line 571, in run                             
    raise CalledProcessError(retcode, process.args,                                                           
subprocess.CalledProcessError: Command '['tesseract', '-l', 'chi_sim+eng+osd+equ',                            
'/tmp/ocrmypdf.io.irxadwgc/000420_ocr.png', '/tmp/ocrmypdf.io.irxadwgc/000420_ocr_hocr',                      
'hocr', 'txt']' died with <Signals.SIGFPE: 8>.                                                                
                                                                                                              
The above exception was the direct cause of the following exception:                                          
                                                                                                              
Traceback (most recent call last):                                                                            
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py",               
line 249, in cli_exception_handler                                                                            
    return fn(options, plugin_manager)                                                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                        
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py",                   
line 190, in _run_pipeline                                                                                    
    optimize_messages = exec_concurrent(context, executor)                                                    
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                    
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py",                   
line 117, in exec_concurrent                                                                                  
    executor(                                                                                                 
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_concurrent.py", line                 
78, in __call__                                                                                               
    self._execute(                                                                                            
  File                                                                                                        
"/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/concurrency.py               
", line 144, in _execute                                                                                      
    result = future.result()                                                                                  
             ^^^^^^^^^^^^^^^                                                                                  
  File "/home/firestar/.miniconda/lib/python3.12/concurrent/futures/_base.py", line 449, in                   
result                                                                                                        
    return self.__get_result()                                                                                
           ^^^^^^^^^^^^^^^^^^^                                                                                
  File "/home/firestar/.miniconda/lib/python3.12/concurrent/futures/_base.py", line 401, in                   
__get_result                                                                                                  
    raise self._exception                                                                                     
  File "/home/firestar/.miniconda/lib/python3.12/concurrent/futures/thread.py", line 58, in run               
    result = self.fn(*self.args, **self.kwargs)                                                               
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py",                   
line 81, in _exec_page_sync                                                                                   
    ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)                                       
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py",                   
line 62, in _image_to_ocr_text                                                                                
    hocr_out, text_out = ocr_engine_hocr(ocr_image_out, page_context)                                         
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_pipeline.py", line                   
665, in ocr_engine_hocr                                                                                       
    ocr_engine.generate_hocr(                                                                                 
  File                                                                                                        
"/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.               
py", line 253, in generate_hocr                                                                               
    tesseract.generate_hocr(                                                                                  
  File "/home/firestar/.miniconda/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py",                  
line 327, in generate_hocr                                                                                    
    raise SubprocessOutputError() from e                                                                      
ocrmypdf.exceptions.SubprocessOutputError                                                                     
[ble: elapsed 899.058s (CPU 713.5%)]
```

**Comment by jbarlow83** [comment]
The error was a floating point exception ("SIGFPE") from Tesseract on page 420.

If you are able to, upgrade to a newer version of Tesseract in case that resolves the issue. To see the current version, run ``tesseract --version`` (and paste the output here in a comment). Since you are using Linux, you may be able to install a newer version using a Ubuntu PPA or similar backport for your Linux distribution. Alternately, you could try building Tesseract latest from source.

If upgrading Tesseract does not work, then I will help you extract the relevant file so we can forward the issue to the Tesseract project.

**Comment by Firestar-Reimu** [comment]
I use archlinux and:
```
$ tesseract --version
tesseract 5.3.4
 leptonica-1.83.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 3.0.0) : libpng 1.6.43 : libtiff 4.6.0 : zlib 1.2.13 : libwebp 1.4.0 : libopenjp2 2.5.2
 Found AVX512BW
 Found AVX512F
 Found AVX512VNNI
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.7.2 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.5
```
I think my tesseract is the latest

**Comment by Firestar-Reimu** [comment]
![image](https://github.com/ocrmypdf/OCRmyPDF/assets/65082432/d00b0372-6db1-4f99-9be1-4bdef27e3cef)

Page 420 look like this, you can extract it (sorry I have no extract page software) to see if the big figure cause the tesseract problem

**Comment by jbarlow83** [comment]
Based on [this issue with tesseract](https://github.com/tesseract-ocr/tesseract/issues/3693), the language "equ" is unreliable and is the cause of these floating point exceptions.

Instead, create a tesseract configuration file, which is just a plain text file containing the text
```
textord_equation_detect=true
```
Save this file as "equations" in the current directory.

Then use `ocrmypdf -l chi_sim+eng --tesseract-config equations ...[rest of your arguments...]`

You should also not include osd as a language. This is not actually a language, but a data package used to determine page orientation that tesseract stores in the same format as its language data.

I will update ocrmypdf to prevent accidental use of the osd and equ language packs. As far as I can see, there is no reason to allow their use.

For reasons not clear to me, Ghostscript fails on your file, but `--output-type pdf --language chi_sim+eng` works.
