### ISSUE TITLE
[Bug]: ocrmypdf 16.3.1 fails on a file on Arch that 13.4.0 on Ubuntu handles well

### ISSUE THREAD

**Issue by Fifis** [ocrmypdf/OCRmyPDF#1329]
### Describe the bug

I installed `ocrmypdf` 16.3.1 via `pipx` and tries OCR’ing a couple of different documents. The error is `ocrmypdf.exceptions.SubprocessOutputError` because tesseract dies with `subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr.png', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr_hocr', 'hocr', 'txt']' died with <Signals.SIGFPE: 8>.`. Individually, tesseract 5.4.0 on the same machine has no problems recognising individual pages. The same PDF can be successfully processed by tesseract 13.4.0 on a different machine with Ubuntu. Then, I tried removing the `pipx` version and installed `ocrmypdf` of the same version from AUR. Same file, same error (Signals.SIGFPE: 8 – floating-point error?..). I hereby enclose the two log files: failure and success.

### Steps to reproduce

```plain text
1. Run `ocrmypdf -j 1 --verbose 2  a.pdf a2.pdf`
2. The subprocess dies.
```

### Files

[a.pdf](https://github.com/user-attachments/files/15792559/a.pdf)
[ocrmypdf-success.log](https://github.com/user-attachments/files/15792563/ocrmypdf-success.log)
[ocrmypdf-error.log](https://github.com/user-attachments/files/15792565/ocrmypdf-error.log)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.), Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

16.3.1 

### Relevant log output

```plain text
~/.local/bin/ocrmypdf -j 1 --verbose 2  a.pdf a2.pdf
  DEBUG ocrmypdf - ocrmypdf 16.3.1                                                                                                                                                                                            __main__.py:59
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']                                                                                                                                                            __init__.py:133
  DEBUG ocrmypdf.subprocess - Found tesseract 5.4.0                                                                                                                                                                          __init__.py:343
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--version']                                                                                                                                                            __init__.py:133
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']                                                                                                                                                                   __init__.py:133
  DEBUG ocrmypdf.subprocess - Found gs 10.3.1                                                                                                                                                                                __init__.py:343
  DEBUG ocrmypdf.subprocess - Running: ['gs', '--version']                                                                                                                                                                   __init__.py:133
  DEBUG ocrmypdf.subprocess - Running: ['tesseract', '--list-langs']                                                                                                                                                         __init__.py:133
  DEBUG ocrmypdf.subprocess.tesseract - stdout/stderr = List of available languages in "/usr/share/tessdata/" (4):                                                                                                            __init__.py:73
eng
fra
osd
rus

  DEBUG ocrmypdf.helpers - pikepdf mmap enabled                                                                                                                                                                               helpers.py:326
  DEBUG ocrmypdf.helpers - os.symlink(a.pdf, /tmp/ocrmypdf.io.1cr5y8l6/origin)                                                                                                                                                helpers.py:179
  DEBUG ocrmypdf.helpers - os.symlink(/tmp/ocrmypdf.io.1cr5y8l6/origin, /tmp/ocrmypdf.io.1cr5y8l6/origin.pdf)                                                                                                                 helpers.py:179
  DEBUG root - Gathering info with 1 thread workers                                                                                                                                                                              info.py:778
  DEBUG ocrmypdf.helpers - pikepdf mmap enabled                                                                                                                                                                               helpers.py:326
  DEBUG PIL.Image - Importing BlpImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing BmpImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing BufrStubImagePlugin                                                                                                                                                                               Image.py:376
  DEBUG PIL.Image - Importing CurImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing DcxImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing DdsImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing EpsImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing FitsImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing FliImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing FpxImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Image: failed to import FpxImagePlugin: No module named 'olefile'                                                                                                                                           Image.py:379
  DEBUG PIL.Image - Importing FtexImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing GbrImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing GifImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing GribStubImagePlugin                                                                                                                                                                               Image.py:376
  DEBUG PIL.Image - Importing Hdf5StubImagePlugin                                                                                                                                                                               Image.py:376
  DEBUG PIL.Image - Importing IcnsImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing IcoImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing ImImagePlugin                                                                                                                                                                                     Image.py:376
  DEBUG PIL.Image - Importing ImtImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing IptcImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing JpegImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing Jpeg2KImagePlugin                                                                                                                                                                                 Image.py:376
  DEBUG PIL.Image - Importing McIdasImagePlugin                                                                                                                                                                                 Image.py:376
  DEBUG PIL.Image - Importing MicImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Image: failed to import MicImagePlugin: No module named 'olefile'                                                                                                                                           Image.py:379
  DEBUG PIL.Image - Importing MpegImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing MpoImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing MspImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PalmImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing PcdImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PcxImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PdfImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PixarImagePlugin                                                                                                                                                                                  Image.py:376
  DEBUG PIL.Image - Importing PngImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PpmImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing PsdImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing QoiImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing SgiImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing SpiderImagePlugin                                                                                                                                                                                 Image.py:376
  DEBUG PIL.Image - Importing SunImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing TgaImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing TiffImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing WebPImagePlugin                                                                                                                                                                                   Image.py:376
  DEBUG PIL.Image - Importing WmfImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing XbmImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing XpmImagePlugin                                                                                                                                                                                    Image.py:376
  DEBUG PIL.Image - Importing XVThumbImagePlugin                                                                                                                                                                                Image.py:376
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 686/686 0:00:00
  DEBUG ocrmypdf.builtin_plugins.tesseract_ocr - Using Tesseract OpenMP thread limit 1                                                                                                                                  tesseract_ocr.py:184
  DEBUG ocrmypdf.helpers - pikepdf mmap enabled                                                                                                                                                                               helpers.py:326
  DEBUG ocrmypdf._pipeline -    1  Rasterize with png16m, rotation 0                                                                                                                                                        _pipeline.py:539
  DEBUG ocrmypdf.subprocess -    1  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=png16m', '-dFirstPage=1', '-dLastPage=1', '-r300.000000x300.000000',                  __init__.py:133
'-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.1cr5y8l6/origin.pdf']
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13                                                                                                                                                                PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'sRGB' 41 1                                                                                                                                                                 PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 54 9                                                                                                                                                                 PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'tEXt' 75 32                                                                                                                                                                PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 119 8192                                                                                                                                                             PngImagePlugin.py:191
  DEBUG ocrmypdf._exec.ghostscript -    1  Rotating output by 0                                                                                                                                                           ghostscript.py:149
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IHDR' 16 13                                                                                                                                                                PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'pHYs' 41 9                                                                                                                                                                 PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    1  STREAM b'IDAT' 62 65536                                                                                                                                                             PngImagePlugin.py:191
  DEBUG ocrmypdf._pipeline -    1  resolution (299.9994, 299.9994)                                                                                                                                                          _pipeline.py:618
  DEBUG ocrmypdf.subprocess -    1  Running: ['tesseract', '-l', 'eng', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr.png', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr_hocr', 'hocr', 'txt']                                              __init__.py:133
  DEBUG ocrmypdf._pipeline -    2  Rasterize with pngmono, rotation 0                                                                                                                                                       _pipeline.py:539
  DEBUG ocrmypdf.subprocess -    2  Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=pngmono', '-dFirstPage=2', '-dLastPage=2', '-r300.000000x300.000000',                 __init__.py:133
'-dPDFSTOPONERROR', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.1cr5y8l6/origin.pdf']
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13                                                                                                                                                                PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2296                                                                                                                                                              PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'default_gray.icc'                                                                                                                                               PngImagePlugin.py:394
  DEBUG PIL.PngImagePlugin -    2  Compression method 0                                                                                                                                                                PngImagePlugin.py:396
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2349 9                                                                                                                                                               PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'tEXt' 2370 32                                                                                                                                                              PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2414 8192                                                                                                                                                            PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IHDR' 16 13                                                                                                                                                                PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'iCCP' 41 2291                                                                                                                                                              PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  iCCP profile name b'ICC Profile'                                                                                                                                                    PngImagePlugin.py:394
  DEBUG PIL.PngImagePlugin -    2  Compression method 0                                                                                                                                                                PngImagePlugin.py:396
  DEBUG PIL.PngImagePlugin -    2  STREAM b'pHYs' 2344 9                                                                                                                                                               PngImagePlugin.py:191
  DEBUG PIL.PngImagePlugin -    2  STREAM b'IDAT' 2365 26893                                                                                                                                                           PngImagePlugin.py:191
  DEBUG ocrmypdf._pipeline -    2  resolution (299.9994, 299.9994)                                                                                                                                                          _pipeline.py:618
  DEBUG ocrmypdf.subprocess -    2  Running: ['tesseract', '-l', 'eng', '/tmp/ocrmypdf.io.1cr5y8l6/000002_ocr.png', '/tmp/ocrmypdf.io.1cr5y8l6/000002_ocr_hocr', 'hocr', 'txt']                                              __init__.py:133
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(0.24, 0, 0, -0.24, 0, 532.08)                                                                                                                                       _hocr.py:193
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 154, 310)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 154, 375)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 443)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 154, 535)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 602)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 694)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 151, 788)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 855)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 151, 922)                                                                                                                                               _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(0.99995, 0.0099995, -0.0099995, 0.99995, 150, 988)                                                                                                                  _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 1055)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 1122)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 152, 1188)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(0.999976, 0.00699983, -0.00699983, 0.999976, 150, 1281)                                                                                                             _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 149, 1348)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 147, 1441)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 146, 1535)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 148, 1602)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 149, 1668)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 147, 1762)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 147, 1854)                                                                                                                                              _hocr.py:310
  DEBUG ocrmypdf.hocrtransform._hocr -    2  eng                                                                                                                                                                                _hocr.py:257
  DEBUG ocrmypdf.hocrtransform._hocr -    2  pikepdf.Matrix(1, 0, 0, 1, 148, 1944)                                                                                                                                              _hocr.py:310
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%   0/686 -:--:--
  ERROR ocrmypdf._pipelines._common - ExitCodeException                                                                                                                                                                       _common.py:259
Traceback (most recent call last):
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py", line 313, in generate_hocr
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/subprocess/__init__.py", line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr.png', '/tmp/ocrmypdf.io.1cr5y8l6/000001_ocr_hocr', 'hocr', 'txt']' died with <Signals.SIGFPE: 8>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
    return fn(options, plugin_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 190, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 117, in exec_concurrent
    executor(
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_concurrent.py", line 78, in __call__
    self._execute(
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 144, in _execute
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 81, in _exec_page_sync
    ocr_out, text_out = _image_to_ocr_text(page_context, ocr_image_out)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 62, in _image_to_ocr_text
    hocr_out, text_out = ocr_engine_hocr(ocr_image_out, page_context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_pipeline.py", line 665, in ocr_engine_hocr
    ocr_engine.generate_hocr(
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 253, in generate_hocr
    tesseract.generate_hocr(
  File "/home/avk/.local/share/pipx/venvs/ocrmypdf/lib/python3.12/site-packages/ocrmypdf/_exec/tesseract.py", line 327, in generate_hocr
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
```

**Comment by jbarlow83** [comment]
Duplicate
