### ISSUE TITLE
[Bug]:  OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Salvodif** [ocrmypdf/OCRmyPDF#1346]
### What were you trying to do?

I was trying to make an ocr of one of my pdf files

### Where are you installing/running from?

PyPI (pip, poetry, pipx, etc.), Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

16.4.1

### What operating system are you working on?

Linux

### Operating system details and version

6.9.7-arch1-1

### Simple sanity checks

- [ ] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF
- [ ] This issue is not about a specific input file

### Relevant log output

```plain text
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
An exception occurred while executing the pipeline                                                                                                                _common.py:284
Traceback (most recent call last):                                                                                                                                              
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler                                       
    return fn(options, plugin_manager)                                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 190, in _run_pipeline                                                   
    optimize_messages = exec_concurrent(context, executor)                                                                                                                      
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/_pipelines/ocr.py", line 145, in exec_concurrent                                                 
    pdf, messages = postprocess(pdf, context, executor)                                                                                                                         
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/_pipelines/_common.py", line 427, in postprocess                                                 
    return optimize_pdf(pdf_out, context, executor)                                                                                                                             
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                             
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/_pipeline.py", line 979, in optimize_pdf                                                         
    output_pdf, messages = context.plugin_manager.hook.optimize_pdf(                                                                                                            
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__                                                                  
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)                                                                                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                               
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec                                                               
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)                                                                                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                        
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall                                                              
    raise exception.with_traceback(exception.__traceback__)                                                                                                                     
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall                                                              
    res = hook_impl.function(*args)                                                                                                                                             
          ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                             
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/builtin_plugins/optimize.py", line 145, in optimize_pdf                                          
    result_path = optimize(input_pdf, output_pdf, context, save_settings, executor)                                                                                             
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                             
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/ocrmypdf/optimize.py", line 708, in optimize                                                              
    pdf.save(target_file, **save_settings)                                                                                                                                      
  File "/home/blackpraedicator/mypipapps/lib/python3.12/site-packages/pikepdf/_methods.py", line 320, in save                                                                   
    self._save(                                                                                                                                                                 
OSError: [Errno 28] No space left on device
```

**Comment by Salvodif** [comment]
> of temporary storage. Ocrmypdf needs several MB per

my system has 32gb plus 8gb of swap

**Comment by jbarlow83** [comment]
How much tmpfs?

**Comment by Salvodif** [comment]
> How

tmpfs           16300248         8  16300240   1% /tmp
