### ISSUE TITLE
[Bug]: Ghostscript can't create a PDF/A-file (Page object was reserved for an Annotation destination)

### ISSUE THREAD

**Issue by JoKalliauer** [ocrmypdf/OCRmyPDF#1349]
### Describe the bug

When I run ocrmypdf on a specific file I get a ghostscript-error "Page object was reserved for an Annotation destination, but no such page was drawn, annotation in output will be invalid.".

I would like to process the file, however skip the convertion to PDF/A, if it fails.

```bash
Processing pages 1 through 19.
Page 1
Page 2
Error: /undefined in --runpdf--
Operand stack:   --nostringval--   --nostringval--   1
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1
%stopped_push   1928   1   3   %oparray_pop   1927   1   3   %oparray_pop   1912   1   3   %oparray_pop   1913   1   3   %oparray_pop   runpdf   runpdf   runpdf   3   1
19   runpdf   %for_pos_int_continue   runpdf
Dictionary stack:   --dict:749/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:7/10(L)--
Current allocation mode is local
Last OS error: Permission deniedGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1
GPL Ghostscript 10.02.1: Page object was reserved for an Annotation destination, but no such page was drawn, annotation in output will be invalid.

SubprocessOutputError: Ghostscript PDF/A rendering failed 
```

### Steps to reproduce

```plain text
1. `wget https://github.com/user-attachments/files/16109877/falsificationX_SteifigkeitstensorX.pdf`
2. `ocrmypdf -v1 -j 1 --optimize 01 -l deu+eng falsificationX_SteifigkeitstensorX.pdf output.pdf  --skip-text`
```

### Files

[falsificationX_SteifigkeitstensorX.pdf](https://github.com/user-attachments/files/16109877/falsificationX_SteifigkeitstensorX.pdf)

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

16.4.1

### Relevant log output

```plain text
ocrmypdf 16.4.1                                                                                                                                                               __main__.py:59
Running: ['tesseract', '--version']                                                                                                                                          __init__.py:133
Found tesseract 5.4.1                                                                                                                                                        __init__.py:343
Running: ['tesseract', '--version']                                                                                                                                          __init__.py:133
Running: ['tesseract', '--version']                                                                                                                                          __init__.py:133
Running: ['gs', '--version']                                                                                                                                                 __init__.py:133
Found gs 10.2.1                                                                                                                                                              __init__.py:343
Running: ['gs', '--version']                                                                                                                                                 __init__.py:133
Running: ['tesseract', '--list-langs']                                                                                                                                       __init__.py:133
stdout/stderr = List of available languages in "/usr/share/tesseract-ocr/5/tessdata/" (3):                                                                                    __init__.py:73
deu
eng
osd

pikepdf mmap enabled                                                                                                                                                          helpers.py:326
os.symlink(falsificationX_SteifigkeitstensorX.pdf, /tmp/ocrmypdf.io.3hj68jyx/origin)                                                                                          helpers.py:179
os.symlink(/tmp/ocrmypdf.io.3hj68jyx/origin, /tmp/ocrmypdf.io.3hj68jyx/origin.pdf)                                                                                            helpers.py:179
Gathering info with 1 thread workers                                                                                                                                             info.py:778
pikepdf mmap enabled                                                                                                                                                          helpers.py:326
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 19/19 0:00:00
Using Tesseract OpenMP thread limit 1                                                                                                                                   tesseract_ocr.py:199
pikepdf mmap enabled                                                                                                                                                          helpers.py:326
    1 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    2 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    1 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
    3 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    1 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
    4 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    2 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
    5 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    2 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
    6 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    3 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
    7 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    3 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
    8 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    4 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
    9 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    4 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   10 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    5 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   11 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    5 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   12 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    6 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   13 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    6 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   14 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    7 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   15 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    7 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   16 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    8 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   17 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    8 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   18 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    9 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   19 skipping all processing on this page                                                                                                                                  _pipeline.py:330
    9 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   10 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   10 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   11 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   11 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   12 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   12 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   13 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   13 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   14 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   14 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   15 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   15 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   16 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   16 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   17 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   17 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   18 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   18 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
   19 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                         _graft.py:140
   19 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                     _graft.py:165
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 19/19 0:00:00
Postprocessing...                                                                                                                                                                 ocr.py:144
os.symlink(/tmp/ocrmypdf.io.3hj68jyx/graft_layers.pdf, /tmp/ocrmypdf.io.3hj68jyx/fix_docinfo.pdf)                                                                             helpers.py:179
Running: ['gs', '--version']                                                                                                                                                 __init__.py:133
Running: ['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None',                                               __init__.py:133
'-sColorConversionStrategy=LeaveColorUnchanged', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2',
'-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.3hj68jyx/fix_docinfo.pdf', '/tmp/ocrmypdf.io.3hj68jyx/pdfa.ps']
GPL Ghostscript 10.02.1 (2023-11-01)                                                                                                                                         __init__.py:108
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.                                                                                                              __init__.py:108
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:                                                                                                   __init__.py:108
see the file COPYING for details.                                                                                                                                            __init__.py:108
Processing pages 1 through 19.                                                                                                                                               __init__.py:108
Page 1                                                                                                                                                                       __init__.py:108
Page 2                                                                                                                                                                       __init__.py:108
Error: /undefined in --runpdf--                                                                                                                                              __init__.py:108
Operand stack:   --nostringval--   --nostringval--   1                                                                                                                       __init__.py:108
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1   %stopped_push __init__.py:108
1928   1   3   %oparray_pop   1927   1   3   %oparray_pop   1912   1   3   %oparray_pop   1913   1   3   %oparray_pop   runpdf   runpdf   runpdf   3   1   19   runpdf
%for_pos_int_continue   runpdf
Dictionary stack:   --dict:749/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:7/10(L)--                                                                      __init__.py:108
Current allocation mode is local                                                                                                                                             __init__.py:108
Last OS error: Permission deniedGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1                                                                                    __init__.py:108
GPL Ghostscript 10.02.1: Page object was reserved for an Annotation destination, but no such page was drawn, annotation in output will be invalid.                           __init__.py:108
PDF/A conversion      ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  11%  2/19 0:00:01
GPL Ghostscript 10.02.1 (2023-11-01)                                                                                                                                      ghostscript.py:297
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 19.
Page 1
Page 2
Error: /undefined in --runpdf--
Operand stack:   --nostringval--   --nostringval--   1
Execution stack:   %interp_exit   .runexec2   --nostringval--   runpdf   --nostringval--   2   %stopped_push   --nostringval--   runpdf   runpdf   false   1
%stopped_push   1928   1   3   %oparray_pop   1927   1   3   %oparray_pop   1912   1   3   %oparray_pop   1913   1   3   %oparray_pop   runpdf   runpdf   runpdf   3   1
19   runpdf   %for_pos_int_continue   runpdf
Dictionary stack:   --dict:749/1123(ro)(G)--   --dict:0/20(G)--   --dict:86/200(L)--   --dict:7/10(L)--
Current allocation mode is local
Last OS error: Permission deniedGPL Ghostscript 10.02.1: Unrecoverable error, exit code 1
GPL Ghostscript 10.02.1: Page object was reserved for an Annotation destination, but no such page was drawn, annotation in output will be invalid.

ExitCodeException                                                                                                                                                             _common.py:259
Traceback (most recent call last):
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_exec/ghostscript.py", line 284, in generate_pdfa
    p = run_polling_stderr(
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/subprocess/__init__.py", line 114, in run_polling_stderr
    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None',
'-sColorConversionStrategy=LeaveColorUnchanged', '-dPDFSTOPONERROR', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2',
'-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.3hj68jyx/fix_docinfo.pdf', '/tmp/ocrmypdf.io.3hj68jyx/pdfa.ps']' returned non-zero exit
status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_pipelines/_common.py", line 249, in cli_exception_handler
    return fn(options, plugin_manager)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_pipelines/ocr.py", line 190, in _run_pipeline
    optimize_messages = exec_concurrent(context, executor)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_pipelines/ocr.py", line 145, in exec_concurrent
    pdf, messages = postprocess(pdf, context, executor)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_pipelines/_common.py", line 420, in postprocess
    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 899, in convert_to_pdfa
    context.plugin_manager.hook.generate_pdfa(
  File "/home/jkalliau/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 131, in generate_pdfa
    ghostscript.generate_pdfa(
  File "/home/jkalliau/.local/lib/python3.10/site-packages/ocrmypdf/_exec/ghostscript.py", line 298, in generate_pdfa
    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed
```

**Comment by jbarlow83** [comment]
The software that generated this PDF created a PDF containing numerous errors. It's a broken file. Specifically information that the PDF says is going to be present in the file turns out to be missing, so it's not the kind of error we can repair.
```
$ qpdf --check issuepdf/1349.pdf
checking issuepdf/1349.pdf
PDF Version: 1.3
File is not encrypted
File is not linearized
WARNING: issuepdf/1349.pdf: file is damaged
WARNING: issuepdf/1349.pdf (object 311 0, offset 650536): expected n n obj
WARNING: issuepdf/1349.pdf: Attempting to reconstruct cross-reference table
WARNING: issuepdf/1349.pdf: object 311 0 not found in file after regenerating cross reference table
qpdf: operation succeeded with warnings
```

Because of this and other issues, Ghostscript fails to produce a PDF/A output. As far as I'm concerned this is correct behavior for ocrmypdf - file is irreparably damaged, so fail to pass it on.

Presumably you have the input LaTeX, so I'd suggesting using a different program to render your LaTeX to PDF - something other than PDFsharp, which seems to be responsible for generating this broken PDF. [Here's some information on producing PDF/A directly from LaTeX](https://www.mathstat.dal.ca/~selinger/pdfa/).

**Comment by JoKalliauer** [comment]
@jbarlow83 : Thank you very much for spending time, looking into details, and suggesting solutions that are not related to your software.

Looking into my files it seems, that I used some software (that uses PDFsharp) to remove the last pages of the PDF.

I donated 10$ to ocrmypdf: [https://opencollective.com/johannes-kalliauer](https://opencollective.com/johannes-kalliauer)

**Comment by jbarlow83** [comment]
Thank you!
