### ISSUE TITLE
[Bug]: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by you-healthtap** [ocrmypdf/OCRmyPDF#1368]
### Describe the bug

When the image pdf file is short, everything is good. However, I encounter a few cases throwing `maximum recursion depth exceeded` error when the PDF is 150 or 200 pages long. Anyway to resolve such problem? Attached an example log.

### Steps to reproduce

```plain text
ocrmypdf.ocr(pdf_path, output_path, force_ocr=True, output_type="pdf")
```

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

16.4.2

### Relevant log output

```plain text
2024-08-02T23:39:55.0429975Z DEBUG:ocrmypdf.hocrtransform._hocr:pikepdf.Matrix(0.24, 0, 0, -0.24, 0, 792)
2024-08-02T23:39:55.0430140Z 2024-08-02 23:39:55,042 DEBUG    [_hocr.py:203] pikepdf.Matrix(0.24, 0, 0, -0.24, 0, 792)
2024-08-02T23:39:55.0430825Z pikepdf.Matrix(0.24, 0, 0, -0.24, 0, 792)
2024-08-02T23:39:55.0431041Z 2024-08-02 23:39:55,042 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431142Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431179Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431241Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431282Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431320Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431414Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431453Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0431789Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0432482Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0432566Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0432767Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433120Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433189Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433555Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433809Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433819Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0433874Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0434613Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0434647Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0434720Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435167Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435257Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435299Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435776Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435857Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0435959Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0436305Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0436309Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0436384Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0437290Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0437794Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0438216Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0439335Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0439582Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0439558Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0439913Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0439978Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0440197Z 2024-08-02 23:39:55,043 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0440579Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0440642Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0440968Z 2024-08-02 23:39:55,044 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0441300Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0441365Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0441364Z 2024-08-02 23:39:55,044 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0441935Z 2024-08-02 23:39:55,044 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0442039Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0442114Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0442164Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0442206Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445150Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445423Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445497Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445537Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445576Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445611Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445647Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445683Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445828Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445869Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445931Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.0445959Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5766243Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5842605Z OCR                   ━━━━━━━━━━━━━━╸                        40%  57/143 0:00:34
2024-08-02T23:39:55.5943586Z 2024-08-02 23:39:55,594 ERROR    [web_server.py:1846] Error in OCR process: maximum recursion depth exceeded
2024-08-02T23:39:55.5943591Z ERROR:root:Error in OCR process: maximum recursion depth exceeded
2024-08-02T23:39:55.5943901Z Error in OCR process: maximum recursion depth exceeded
2024-08-02T23:39:55.5944293Z 2024-08-02 23:39:55,594 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5944632Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5944793Z Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5945024Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.5964950Z 2024-08-02 23:39:55,596 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.6015344Z 2024-08-02 23:39:55,601 WARNING  [__init__.py:137] Queue is full. Dropping telemetry.
2024-08-02T23:39:55.6038418Z WARNING:opencensus.common.schedule:Queue is full. Dropping telemetry.
2024-08-02T23:39:55.8066825Z Process Process-1:
2024-08-02T23:39:55.8670383Z Traceback (most recent call last):
2024-08-02T23:39:55.8672814Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8673280Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8673326Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8673396Z     raise Full
2024-08-02T23:39:55.8673674Z queue.Full
2024-08-02T23:39:55.8683347Z
2024-08-02T23:39:55.8683594Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8683633Z
2024-08-02T23:39:55.8683694Z Traceback (most recent call last):
2024-08-02T23:39:55.8684539Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8684627Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8684695Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8684749Z     raise Full
2024-08-02T23:39:55.8684801Z queue.Full
2024-08-02T23:39:55.8684969Z
2024-08-02T23:39:55.8685172Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8685211Z
2024-08-02T23:39:55.8685248Z Traceback (most recent call last):
2024-08-02T23:39:55.8686026Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8686194Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8686247Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8686290Z     raise Full
2024-08-02T23:39:55.8686326Z queue.Full
2024-08-02T23:39:55.8686363Z
2024-08-02T23:39:55.8686406Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8686469Z
2024-08-02T23:39:55.8686508Z Traceback (most recent call last):
2024-08-02T23:39:55.8687164Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8687289Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8687332Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8687383Z     raise Full
2024-08-02T23:39:55.8687407Z queue.Full
2024-08-02T23:39:55.8687841Z
2024-08-02T23:39:55.8688393Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8688455Z
2024-08-02T23:39:55.8688503Z Traceback (most recent call last):
2024-08-02T23:39:55.8688666Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8688778Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8688822Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8688870Z     raise Full
2024-08-02T23:39:55.8688914Z queue.Full
2024-08-02T23:39:55.8688954Z
2024-08-02T23:39:55.8689025Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8689064Z
2024-08-02T23:39:55.8689108Z Traceback (most recent call last):
2024-08-02T23:39:55.8689590Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8689697Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8689762Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8689837Z     raise Full
2024-08-02T23:39:55.8689889Z queue.Full
2024-08-02T23:39:55.8690057Z
2024-08-02T23:39:55.8690219Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8690268Z
2024-08-02T23:39:55.8690315Z Traceback (most recent call last):
2024-08-02T23:39:55.8690871Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8691003Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8691062Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8691113Z     raise Full
2024-08-02T23:39:55.8691167Z queue.Full
2024-08-02T23:39:55.8691218Z
2024-08-02T23:39:55.8691309Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8691355Z
2024-08-02T23:39:55.8691408Z Traceback (most recent call last):
2024-08-02T23:39:55.8691668Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8691769Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8691809Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8691874Z     raise Full
2024-08-02T23:39:55.8691914Z queue.Full
2024-08-02T23:39:55.8692058Z
2024-08-02T23:39:55.8692208Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8692278Z
2024-08-02T23:39:55.8692323Z Traceback (most recent call last):
2024-08-02T23:39:55.8692556Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8692625Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8692672Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8692733Z     raise Full
2024-08-02T23:39:55.8692772Z queue.Full
2024-08-02T23:39:55.8692811Z
2024-08-02T23:39:55.8692854Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8692892Z
2024-08-02T23:39:55.8693017Z Traceback (most recent call last):
2024-08-02T23:39:55.8693539Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8693693Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8693740Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8693821Z     raise Full
2024-08-02T23:39:55.8693864Z queue.Full
2024-08-02T23:39:55.8693902Z
2024-08-02T23:39:55.8694199Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8694432Z
2024-08-02T23:39:55.8694481Z Traceback (most recent call last):
2024-08-02T23:39:55.8694637Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8694717Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8694768Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8694823Z     raise Full
2024-08-02T23:39:55.8694871Z queue.Full
2024-08-02T23:39:55.8694918Z
2024-08-02T23:39:55.8694970Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8695017Z
2024-08-02T23:39:55.8695074Z Traceback (most recent call last):
2024-08-02T23:39:55.8695519Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8695618Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8695644Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8695667Z     raise Full
2024-08-02T23:39:55.8695691Z queue.Full
2024-08-02T23:39:55.8695716Z
2024-08-02T23:39:55.8695741Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8695780Z
2024-08-02T23:39:55.8695812Z Traceback (most recent call last):
2024-08-02T23:39:55.8696220Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8696331Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8696387Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8696438Z     raise Full
2024-08-02T23:39:55.8696564Z queue.Full
2024-08-02T23:39:55.8696695Z
2024-08-02T23:39:55.8696760Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8696808Z
2024-08-02T23:39:55.8696857Z Traceback (most recent call last):
2024-08-02T23:39:55.8697221Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8697342Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8697399Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8697440Z     raise Full
2024-08-02T23:39:55.8697501Z queue.Full
2024-08-02T23:39:55.8697634Z
2024-08-02T23:39:55.8697702Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8697727Z
2024-08-02T23:39:55.8697750Z Traceback (most recent call last):
2024-08-02T23:39:55.8698352Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8698493Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8698538Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8698583Z     raise Full
2024-08-02T23:39:55.8698622Z queue.Full
2024-08-02T23:39:55.8698664Z
2024-08-02T23:39:55.8698706Z During handling of the above exception, another exception occurred:
2024-08-02T23:39:55.8698742Z
2024-08-02T23:39:55.8698816Z Traceback (most recent call last):
2024-08-02T23:39:55.8699138Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8699232Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.8699286Z   File "/usr/local/lib/python3.11/queue.py", line 137, in put
2024-08-02T23:39:55.8699336Z     raise Full
2024-08-02T23:39:55.8699470Z queue.Full
2024-08-02T23:39:55.8716584Z
2024-08-02T23:39:55.8735455Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8754207Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 135, in put
2024-08-02T23:39:55.8914571Z   File "/app/./llm/webserver/web_server.py", line 1843, in _ocrmypdf_process
2024-08-02T23:39:55.8914741Z     ocrmypdf.ocr(pdf_path, output_path, force_ocr=True, output_type="pdf")
2024-08-02T23:39:55.8914771Z   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/api.py", line 380, in ocr
2024-08-02T23:39:55.8914797Z     return run_pipeline(options=options, plugin_manager=plugin_manager)
2024-08-02T23:39:55.8914821Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-02T23:39:55.8914847Z   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 223, in run_pipeline
2024-08-02T23:39:55.8914901Z     return _run_pipeline(options, plugin_manager)
2024-08-02T23:39:55.8914927Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-02T23:39:55.8914952Z   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_pipelines/ocr.py", line 190, in _run_pipeline
2024-08-02T23:39:55.8964992Z   File "/usr/local/lib/python3.11/logging/__init__.py", line 1501, in warning
2024-08-02T23:39:55.8982984Z     self.callHandlers(record)
2024-08-02T23:39:55.9000011Z     self.handle(record)
2024-08-02T23:39:55.9018025Z   File "/usr/local/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
2024-08-02T23:39:55.9035505Z     self._queue.put(item, block, timeout)
2024-08-02T23:39:55.9164583Z   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-08-02T23:39:55.9164817Z     self.run()
2024-08-02T23:39:55.9164874Z   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-08-02T23:39:55.9164924Z     self._target(*self._args, **self._kwargs)
2024-08-02T23:39:55.9164973Z   File "/app/./llm/webserver/web_server.py", line 1846, in _ocrmypdf_process
2024-08-02T23:39:55.9165021Z     logging.error(f"Error in OCR process: {e}")
2024-08-02T23:39:55.9165114Z   File "/usr/local/lib/python3.11/logging/__init__.py", line 2108, in error
2024-08-02T23:39:55.9175205Z     self._queue.put(record, block=False)
2024-08-02T23:39:55.9192841Z     return old_callhandlers(self, record)
2024-08-02T23:39:55.9211428Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 137, in put
2024-08-02T23:39:55.9229981Z   File "/usr/local/lib/python3.11/site-packages/opencensus/common/schedule/__init__.py", line 137, in put
2024-08-02T23:39:55.9467324Z ERROR:root:Refined PDF is zero size or not created
2024-08-02T23:39:55.9467551Z Refined PDF is zero size or not created
2024-08-02T23:39:55.9468283Z 2024-08-02 23:39:55,946 ERROR    [web_server.py:1741] Refined PDF is zero size or not created
2024-08-02T23:39:56.1127833Z ERROR:root:Return error status code 500 with 'Refined PDF creation failed'
2024-08-02T23:39:56.1127907Z 2024-08-02 23:39:56,112 ERROR    [service_helper.py:209] Return error status code 500 with 'Refined PDF creation failed'
2024-08-02T23:39:56.1128157Z Return error status code 500 with 'Refined PDF creation failed'
```

**Comment by jbarlow83** [comment]
Some third party library or application seems to be installed and is causing some unusual issues, leading to these messages:

>opencensus.common.schedule:Queue is full. Dropping telemetry.

Please demonstrate that the issue in a clean virtual environment with nothing except ocrmypdf installed, and provide the test file, which is required for this issue.

**Comment by you-healthtap** [comment]
> Some third party library or application seems to be installed and is causing some unusual issues, leading to these messages:
> 
> > opencensus.common.schedule:Queue is full. Dropping telemetry.
> 
> Please demonstrate that the issue in a clean virtual environment with nothing except ocrmypdf installed, and provide the test file, which is required for this issue.

You are right. It is caused by logging level DEBUG. After changing to INFO, the problem is gone
