### ISSUE TITLE
Extract single pages from a double-page layout and more

### ISSUE THREAD

**Issue by sojusnik** [ocrmypdf/OCRmyPDF#330]
Many thanks for your sophisticated tool!

I'm hoping that it will improve my academic reading workflow by turning scanned PDFs into annotatable documents to be processed afterwards with [Zotero](https://www.zotero.org/) and the [ZotFile](http://zotfile.com/) plugin. The latter automatically extracts annotations from PDFs appending the corresponding page number. Because nearly all of my PDFs I have to read have a double-page layout (= two actual pages on one PDF page) and normally don't start with page one (they usually contain only a chapter of a book), I have to create one page per sheet (as depicted [here](https://i.imgur.com/viHMwWa.png)) and adjust the page number manually, in order to have the correct page number after extracting the annotations with ZotFile. You may have noticed that the screenshot is taken from [unpaper](https://github.com/Flameeyes/unpaper/blob/master/doc/basic-concepts.md#input-and-output-image-files). Because your tool is already using unpaper and doing some preprocessing magic, I appreciate your professional opinion on the following questions:

1. Can OCRmyPDF automatically extract pages from a double-page layout and create one page per sheet in the output PDF? Ideally, those pages should be aligned, the blank pages removed and the page margins cropped slightly.

2. Is the automatic extraction of pages reliable from your experience? Or are graphical tools like [krop](http://arminstraub.com/software/krop) or [briss](http://briss.sourceforge.net/) more suitable for this?

3. What is the most convenient way to change the page number of a PDF to the actual page number of the scanned document? This is essential, so that Zotfile can append the corresponding page number to the annotations.

As a humanities student I'm not very tech-savvy and appreciate every help, especially when the deadline for my master thesis is slowly getting closer and closer.

Using `OCRmyPDF` 7.4.0 on `Ubuntu` 18.10 with `unpaper` 6.1 and `tesseract` 4.0.0-115-ge3a3.

Best wishes!

**Comment by jbarlow83** [comment]
We could say there's two main workflows people have when they want to scan-clean-OCR. There's the mass production, archival use case, where you have large batch jobs, you can't review everything individually; and there's the bespoke approach where you are prepared to review everything and want to address details. ocrmypdf is biased towards the former use case, so the image cleaning tools tend to be biased towards safe operations that try to improve things and do no harm. I use unpaper but with several `--no-automatic-this-or-that` options that turn off anything that might be dangerous.

I've generally found that automatic page segmentation will fail often enough to be annoying, especially if the scans are not really clean going in. What I do for individual review is ScanTailor for cleanup, and img2pdf to bundle the ScanTailor output images and ocrmypdf to finalize. ScanTailor does the sort of automatic cleanup that unpaper does, but significantly, gives you a GUI to fix the mistakes. This unfortunately can be quite tedious but the results look great. 

I'd certainly welcome the contribution if someone offered improvements to support a page splitting workflow (I realize you're say thing that's not quite your comfort zone) but unfortunately I don't think I'd get much personal/business use from it so I can't justify the effort. Maybe if I do another degree it will happen :).

qpdf (a library I use to manage PDFs) is adding a feature to manage PDF page labels (how page numbers are changed). I'll be able to add that ocrmypdf fairly easily.

**Comment by sojusnik** [comment]
Thus the `unpaper` command `--output-pages 2` (described [here](https://github.com/Flameeyes/unpaper/blob/master/doc/basic-concepts.md#input-and-output-image-files)) can't be applied within `ocrmypdf`, since it's already converting pdfs into images for preprocessing?

You mention `--clean-final` or `--deskew` in the documentation. So `ocrmypdf` is indeed capable of creating altered (optimized) pdfs too. As you've mentioned before, the results could not meet the expectations, but I'm willing to try it out.

> qpdf (a library I use to manage PDFs) is adding a feature to manage PDF page labels (how page numbers are changed). I'll be able to add that ocrmypdf fairly easily.

Great, thanks!

**Comment by jbarlow83** [comment]
Relevant code is in src/ocrmypdf/exec/unpaper.py. You must fork to make the kind of changes that interest you.

You might also find the -k option as well. You use -k and force ocrmypdf to abort when it hits the unpaper step, then go to the temporary folder it and work on the images it generates. That would use ocrmypdf to rasterize the page images.

**Comment by sojusnik** [comment]
After playing around I theoretically found a simple solution for splitting double-pages in `ocrmypdf` without the necessity to implement a completely new workflow. However, some (hopefully easy to implement) adjustments have to be made.

In contrast to `ocrmypdf`, [pdfsandwich](http://www.tobias-elze.de/pdfsandwich/) is extensively using the preprocessing features of `unpaper`. Therefore, [this](https://mega.nz/#!y8YnVQrC!npP_l6DW7dn4twV06wtusIgJxctG2w9jkqLYvTdvyhc) scanned pdf was turned into [this](https://mega.nz/#!24QDiayJ!399fJ-ageTpwA-9s_e4C5RTPRdX8dV1k6-pUCHibfgI) one only by using `pdfsandwich -layout double James.pdf`. All disturbing artifacts were automatically removed allowing the pages to be centered and aligned for the next step – a simple vertical cut in the middle of the pdf with `mutool poster -x 2 James_ocr.pdf`– resulting in a [single-page pdf](https://mega.nz/#!T5YTUAQS!0A1hCsdoRnNMI_GvVL424vrO2j4zlnaQNnhAX417woM) with perfect page margins. Maybe the tools `ocrmypdf` is using are already capable of doing so, without `mutool`?

The only obvious downside of `pdfsandwich` is that the quality of the output pdf is inferior to pdf that `ocrmypdf` creates, as shown [here](https://mega.nz/#!nxIXyATb!muLVp8hbt0cfLNsmfR4YvepUELj86tPCl3wzCCI6PbQ). I'm wondering if it's due to the preprocessing of `unpaper` or the tools/methods `pdfsandwich` is using?

If you think that `ocrmypdf` will produce a better pdf even with those preprocessing steps `unpaper` does, then implementing a way of allowing to do so in `ocrmypdf` should be considered, since it's a very common use case. One way to implement this functionality would be to allow passing commands to `unpaper`while `ocrmypdf` is doing its magic. `pdfsandwich` allows to do this with `-unpo` as described [here](http://www.tobias-elze.de/pdfsandwich/).

This way `ocrmypdf` would stay as it is, suitable for unattended batch jobs without harming the pdf, with an powerful option to use all features `unpaper`is providing without the tedious forking of `src/ocrmypdf/exec/unpaper.py` or handling with the pictures in the temp folder after using the `-k` parameter. To be able to use the full potential of `unpaper` you have to manually define f.i. `-layout double` for every document anyway. Since we already have a `--deskew` option and the like, such an option wouldn't contradict with the handling of `ocrmypdf`, but make it more useful!

Since I don't have any programming experience, I can't really estimate the effort to enable the above mentioned, but I'm convinced that the effort will pay off greatly.

**Comment by jbarlow83** [comment]
I don't think it would be too difficult to create a pathway for using more of the unpaper options - I will see about adding that.

I don't think I will add `mutool poster` but instead mention it as a procedure in the documentation. It sounds like mutool already does a good job at that (and would cover other, more general cases).

**Comment by sojusnik** [comment]
> I don't think it would be too difficult to create a pathway for using more of the unpaper options - I will see about adding that.

Great news! Can't wait to try it out and boost my reading/annotating!

Just a reminder: the new `unpaper` parameter should override the values in `src/ocrmypdf/exec/unpaper.py`. I think that f.i. `ocrmypdf --unpaper "--layout double --no-noisefilter" file.pdf` would look great! 

Do you know if it's actually possible to combine `ocrmypdf` with `mutools` in one command, as for example `ocrmypdf --rotate-pages --deskew -l eng+deu input.pdf output.pdf | mutool poster -x 2 output.pdf`? The aim is that `mutool` takes the result from `ocrmypdf` to split the file in one go".

**Comment by jbarlow83** [comment]
Yes, I think I will do it like that, a separate argument for unpaper arguments.

ocrmypdf will write to stdout but mutool does not read from stdin. You can work around with that process substitution, so `mutool poster -x 2 (ocrmypdf ... in.pdf - | psub) mutool_out.pdf` in fish-shell or I think it might be `mutool -x 2 <(ocrmypdf ...in.pdf -) mutool_out.pdf` in bash.

**Comment by sojusnik** [comment]
I've tried the following command, but it failed:

```
$:~/Downloads$ mutool poster -x 2 <(ocrmypdf test.pdf -) test_split.pdf
error: cannot seek: Illegal seek
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot seek: Illegal seek
uncaught error: cannot seek: Illegal seek
$:~/Downloads$ WARNING -    4: [tesseract] lots of diacritics - possibly poor OCR
WARNING -    6: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   20: [tesseract] lots of diacritics - possibly poor OCR
WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
   INFO - Optimize ratio: 1.00 savings: 0.0%
  ERROR - Traceback (most recent call last):
  File "/home/sojusnik/.local/lib/python3.6/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions
    register_cleanup, touch_files_only)
  File "/home/sojusnik/.local/lib/python3.6/site-packages/ruffus/task.py", line 544, in job_wrapper_io_files
    ret_val = user_defined_work_func(*params)
  File "/home/sojusnik/.local/lib/python3.6/site-packages/ocrmypdf/_pipeline.py", line 931, in copy_final
    copyfileobj(input_stream, sys.stdout.buffer)
  File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
BrokenPipeError: [Errno 32] Broken pipe
```

Same applies to `mutool poster -x 2 <(ocrmypdf test.pdf -)`. I've deleted the last part, because the original syntax looks like this: `mutool poster -x 2 file.pdf`.

Any ideas why?

> Yes, I think I will do it like that, a separate argument for unpaper arguments.

Can you give a rough estimate for the implementation of this feature? I'm willing to speed things up with a donation if it would help, but don't expect much from a humanities student. My deadline is coming nearer and I desperately need a reliable and efficient way to OCR scanned pdfs.

Many thanks in advance!

**Comment by jbarlow83** [comment]
It looks like mutool is trying to seek within data being piped to it, which is not allowed. You'll have to write a little script and do it steps. See the Batch jobs section of the docs: https://ocrmypdf.readthedocs.io/en/latest/batch.html?highlight=parallel#batch-jobs

I pushed `--unpaper-args` to the feature/unpaper-args branch. It needs more hardening before it goes into master, but it will work for you.

I will set up a donation button soon, just looking into options. I appreciate the thought. It will probably be an hour of work after I write some tests for it.

**Comment by sojusnik** [comment]
> It looks like mutool is trying to seek within data being piped to it, which is not allowed. You'll have to write a little script and do it steps. See the Batch jobs section of the docs: https://ocrmypdf.readthedocs.io/en/latest/batch.html?highlight=parallel#batch-jobs

Thanks! I'll try to find a way how to deal with that.

> I pushed `--unpaper-args` to the feature/unpaper-args branch. It needs more hardening before it goes into master, but it will work for you.

Great! I don't know if it's the right way to install this, but I did the following:
- Downloaded https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
- Removed the `ocrmypdf` folder under `~/.local/lib/python3.6/site-packages/ocrmypdf/`
- Replaced it with the `ocrmypdf` folder from `~/Downloads/OCRmyPDF-feature-unpaper-args/src/ocrmypdf/` after extracting the .zip file.

But even with the new unpaper arguments my output.pdf looks like [before](https://mega.nz/#!nxIXyATb!muLVp8hbt0cfLNsmfR4YvepUELj86tPCl3wzCCI6PbQ) (this one was created with `--deskew`, the following not). [Here](https://mega.nz/#!2hIAnYIC!npP_l6DW7dn4twV06wtusIgJxctG2w9jkqLYvTdvyhc) is the unaltered pdf, and [here](https://mega.nz/#!qoIUQC6Y!URvn7VaGknPsXTirZD79IsE3nukZCUq_d3rEYlhOfB0) is the output. I've used the following command:

```
$:~/Downloads/OCR$ ocrmypdf --clean --unpaper-args '--layout double' test.pdf testOCR.pdfWARNING -    5: [tesseract] lots of diacritics - possibly poor OCR
WARNING -    4: [tesseract] lots of diacritics - possibly poor OCR
WARNING -   20: [tesseract] lots of diacritics - possibly poor OCR
WARNING - Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
   INFO - Optimize ratio: 1.00 savings: 0.0%
   INFO - Output file is a PDF/A-2B (as expected)
$:~/Downloads/OCR$ ocrmypdf --version
8.0.0
```

Additionally, you'll also see that the OCRed text is not aligned with the scan any more.

**Comment by sojusnik** [comment]
> I think it may be best to uninstall ocrmypdf, and then install with `pip install --user https://github.com/user/repository/archive/feature/unpaper-args.zip`. It's best to let the Python tools manage their folders since it can be unpredictable.

Ok. Uninstalling went well with `pip3 uninstall ocrmypdf`, but installing not:

```
$ pip install --user https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
Collecting https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
  Downloading https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
     | 12.6MB 28.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-RowWhf-build/setup.py", line 140
        print(f'Checking for {program} >= {need_version}...')
                                                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-RowWhf-build/


$ pip3 install --user https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
Collecting https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
  Downloading https://github.com/jbarlow83/OCRmyPDF/archive/feature/unpaper-args.zip
     \ 12.5MB 14.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-v_g6m_iu-build/setup.py", line 276, in <module>
        'Tracker': 'https://github.com/jbarlow83/ocrmypdf/issues'
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-v_g6m_iu-build/.eggs/setuptools_scm-3.2.0-py3.6.egg/setuptools_scm/integration.py", line 23, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/tmp/pip-v_g6m_iu-build/.eggs/setuptools_scm-3.2.0-py3.6.egg/setuptools_scm/__init__.py", line 144, in get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-v_g6m_iu-build/.eggs/setuptools_scm-3.2.0-py3.6.egg/setuptools_scm/__init__.py", line 111, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-v_g6m_iu-build'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-v_g6m_iu-build/
```

I've tried several combinations of `pip3 install --user git+https://github.com/jbarlow83/OCRmyPDF.git …` too, but never achieved to pull the `unpaper-args` branch.

BTW, is it better to use pip or pip3 in this case?

> If you do `--clean --clean-final` it works, because that mode works in a way that allows for the text to have moved. (For the test image I used, unpaper apparently decided to not reposition the text, so I didn't notice this.) `--clean` only cleans the image that is sent for OCR (allowing you improve OCR quality without changing output appearance).

Sorry, my fault. Thought that `--clean` was enough. In combination with `--clean-final` it works as expected, thanks!
