### ISSUE TITLE
cx_Freeze support - packaging on Windows

### ISSUE THREAD

**Issue by Faisalsouz** [ocrmypdf/OCRmyPDF#488]
**if __name__ == '__main__':
                freeze_support()**

**I am using windows and have installed tesseract ocr and goshscript  as a 'exe' file in window
**

**Getting this error**

```python
Scan: 100%|██████████| 2/2 [00:00<00:00, 662.82page/s]
OCR:   0%|          | 0.0/2.0 [00:00<?, ?page/s]C:\Users\fkhalil\primeStone\docrecog\sampleDocs\nachtrag.pdf C:\Users\fkhalil\primeStone\docrecog\sampleDocs\out_nachtrag.pdf
C:\Users\fkhalil\primeStone\docrecog\sampleDocs\nachtrag.pdf C:\Users\fkhalil\primeStone\docrecog\sampleDocs\out_nachtrag.pdf
Scan: 100%|██████████| 2/2 [00:00<00:00, 501.47page/s]
Scan: 100%|██████████| 2/2 [00:00<00:00, 499.17page/s]
OCR:   0%|          | 0.0/2.0 [00:00<?, ?page/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 263, in run_path
OCR:   0%|          | 0.0/2.0 [00:00<?, ?page/s]
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fkhalil\primeStone\docrecog\ocr.py", line 10, in <module>
    ocrmypdf.ocr(in_path,out_path,language='deu',)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\api.py", line 263, in ocr
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return run_pipeline(options, api=True)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\_sync.py", line 391, in run_pipeline
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 116, in spawn_main
    exec_concurrent(context)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\_sync.py", line 272, in exec_concurrent
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 125, in _main
    pool = Pool(
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\context.py", line 119, in Pool
    prepare(preparation_data)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 236, in prepare
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 212, in __init__
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    self._repopulate_pool()
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    main_content = runpy.run_path(main_path,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 263, in run_path
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 96, in _run_module_code
    w.start()    _run_code(code, mod_globals, init_globals,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\runpy.py", line 86, in _run_code

  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\process.py", line 121, in start
    exec(code, run_globals)
  File "C:\Users\fkhalil\primeStone\docrecog\ocr.py", line 10, in <module>
    self._popen = self._Popen(self)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\context.py", line 326, in _Popen
    ocrmypdf.ocr(in_path,out_path,language='deu',)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\api.py", line 263, in ocr
    return Popen(process_obj)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    return run_pipeline(options, api=True)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\_sync.py", line 391, in run_pipeline
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    exec_concurrent(context)
  File "C:\Users\fkhalil\vritualEnvPrimeStone\venv_prime_stone\lib\site-packages\ocrmypdf\_sync.py", line 272, in exec_concurrent
    _check_not_importing_main()
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    pool = Pool(
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\context.py", line 119, in Pool
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\fkhalil\appdata\local\programs\python\python38\Lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.


```

**To Reproduce**

```python
import ocrmypdf
import os
input_file='nachtrag.pdf'
output_file='out_'+input_file
in_path=os.path.join(r"C:\Users\fkhalil\primeStone\docrecog\sampleDocs",input_file)
out_path=os.path.join(r"C:\Users\fkhalil\primeStone\docrecog\sampleDocs",output_file)
ocrmypdf.ocr(in_path,out_path,language='deu')

```

**System:**
- python version 3.8
- windows 10
- pdf created from MS words with scanned pictures

**Sample file**

[nachtrag.pdf](https://github.com/jbarlow83/OCRmyPDF/files/4154877/nachtrag.pdf)

**Comment by jbarlow83** [comment]
Sorry, I can't help with this. I really don't know anything about cx_freeze or how to use it. I suggest going to the cx_Freeze support forums for guidance. ocrmypdf is a worst case scenario for packaging in that  it uses multiprocessing, threads, subprocesses, signals, and C library calls.

If you want to make a pull request to facilitate executable packaging I would generally be interested.

**Comment by Gothic860** [comment]
Its old but i had the same problem. The solution for me was:

if __name__ == '__main__':
#your code#
