### ISSUE TITLE
Error in post-processing on "bag of images" PDF

### ISSUE THREAD

**Issue by Jmuccigr** [ocrmypdf/OCRmyPDF#846]
**Describe the bug**
Error report in post processing of PDF that contains png and Group4 tiff files. I can't tell which images are giving a problem, but there are two error reports and two png files created with imagemagick to be 2-bit grayscale. The output PDF seems ok. Here's the error:
```
While extracting image xref 62, an error occurred
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/12.7.0_1/libexec/lib/python3.9/site-packages/ocrmypdf/optimize.py", line 269, in extract_images
    result = extract_fn(
  File "/usr/local/Cellar/ocrmypdf/12.7.0_1/libexec/lib/python3.9/site-packages/ocrmypdf/optimize.py", line 204, in extract_image_generic
    pim.as_pil_image().save(png_name(root, xref))
  File "/usr/local/Cellar/ocrmypdf/12.7.0_1/libexec/lib/python3.9/site-packages/pikepdf/models/image.py", line 719, in as_pil_image
    im = self._extract_transcoded()
  File "/usr/local/Cellar/ocrmypdf/12.7.0_1/libexec/lib/python3.9/site-packages/pikepdf/models/image.py", line 527, in _extract_transcoded
    if self.mode in {'DeviceN', 'Separation'}:
  File "/usr/local/Cellar/ocrmypdf/12.7.0_1/libexec/lib/python3.9/site-packages/pikepdf/models/image.py", line 271, in mode
    raise NotImplementedError(
NotImplementedError: Not sure how to handle PDF image of this type
```

**To Reproduce**
I'm just doing a simple:

```bash
ocrmypdf -l ita input.pdf output.pdf
```

**Example file**
I can provide an example off-line.

**Expected behavior**
No errors occur.

**System**
 - OS: macOS
 - OCRmyPDF Version: 12.7.0
 - Homebrew install

**Comment by jbarlow83** [comment]
The PDF contains some images formatted as if they were going to be used in a professional print production environment (i.e. specifying non-CMYK inks). Since these are rare in scanned PDFs I don't plan to do anything special to optimize them.

The error here isn't ideal but also not a problem - the optimizer should ignore the file. I will have to make it trap the exception and print a little info image instead, that an image was skipped.

**Comment by jbarlow83** [comment]
Would you mind checking if this is fixed on the most recent ocrmypdf and pikepdf? I seem to have misplaced the files you sent.

**Comment by gladk** [comment]
Same happens on Debian Bookworm, and on all my scanned pictures. Would it be catch an exception somehow? Thanks!

**Comment by jbarlow83** [comment]
@gladk Please open a new issue and provide as much detail as you can. There are other reasons that error message might be triggered... and it would be really weird for a scanner to produce CMYK images.

**Comment by gladk** [comment]
I have exactly the same error output described in the initial message. I am attaching just a scanned PDF from my scanner: it is empty but producing such an error. I do not see problem with the recognized document: everything is working as expected. Only this exception is thrown.
[ScannedDocument.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7779750/ScannedDocument.pdf)

**Comment by jbarlow83** [comment]
Fixed in the upcoming v17.6.0 (commit 58642d84).

As discussed, the underlying situation was never a problem — the optimizer is best-effort, so an image it can't process is simply left unchanged and the output PDF stays valid. The only issue was the reporting: extraction failures were logged with `log.exception`, printing a full traceback at ERROR level that looked alarming.

The optimizer now traps these failures with a concise warning instead:

```
xref N: this image could not be processed by the optimizer and was left unchanged. The output file is still valid.
```

The full traceback is still available at debug verbosity (`-v 1`) for diagnosis.

Note that the original `NotImplementedError` path is also largely obsolete on modern pikepdf, which now handles `Separation`/`DeviceN` colorspaces and raises a recognized, already-handled exception. @gladk's sample file no longer reproduces any error. Closing as fixed.
