### ISSUE TITLE
IMGUTILS: Picture size is invalid

### ISSUE THREAD

**Issue by bennetrr** [ocrmypdf/OCRmyPDF#888]
**Describe the bug**
I get an exception when I try to ocr a pdf with very large images.

**To Reproduce**
I run OCRmyPDF with this api call:
```python
ocr(input_file, output_file, output_type='pdfa', force_ocr=True, deskew=True, clean=True, pdf_renderer='hocr', optimize=2, language='deu', jobs=6, max_image_mpixels=1000, keep_temporary_files=True)
```
I cannot share the original pdf file, but I recreated this pdf file with the exact sizes of the original pdf. The error messages are the same.
[test.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7830074/test.pdf)

**Stacktrace / Logs**
```python
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 192, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 161, in make_intermediate_images
    ocr_image = preprocess(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 108, in preprocess
    image = preprocess_clean(image, page_context)
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 497, in preprocess_clean
    unpaper.clean(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 134, in clean
    run(input_file, output_file, dpi=dpi, mode_args=unpaper_args)
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 87, in run
    external_run(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 52, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '400.006945', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmpmb1qoinx/input.pnm', '/tmp/tmpmb1qoinx/output.ppm']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/bennet/daten/wemogy/pdf/src/ocr_deskew.py", line 29, in ocr_deskew
    ocr(input_file, output_file, output_type='pdfa', force_ocr=True, deskew=True,
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/media/bennet/daten/wemogy/pdf/venv/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
subprocess.CalledProcessError: Command '['unpaper', '-v', '--dpi', '400.006945', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmpmb1qoinx/input.pnm', '/tmp/tmpmb1qoinx/output.ppm']' returned non-zero exit status 1.
python-BaseException
```

```python
str(__exception__[1].stdout, 'utf-8')
```
```
[ppm @ 0x56279faede80] [IMGUTILS @ 0x7fff6a6ff190] Picture size 23719x13215 is invalid
[ppm @ 0x56279faede80] [IMGUTILS @ 0x7fff6a6ff190] Picture size 23719x13215 is invalid
[ppm @ 0x56279faede80] Invalid scale.
unpaper: error: unable to open file /tmp/tmpmb1qoinx/input.pnm: End of file
Try 'man unpaper' for more information.
unpaper 6.1
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /tmp/tmpmb1qoinx/input.pnm -> /tmp/tmpmb1qoinx/output.ppm
```

**System**
 - OS: Ubuntu 21.04 and Mac OS (latest version)
 - OCRmyPDF Version: 13.1.1
 - Installation Type: OCRmyPDF with pip, dependencies with apt / brew

**Comment by jbarlow83** [comment]
The maximum size for unpaper is INT_MAX/8 or 2^31/2^3 = 2^28 = 256 Mpixel.
23719×13215 is 313 Mpixels.

If you turn off `--clean` this should work fine.

Limit is enforced here in libavutil::imgutils, a dependency of unpaper. This is, unfortunately, a hardcoded limit in that library even though images above 256 Mpixels are quite reasonable for large format scanners, panoramas, etc.
https://ffmpeg.org/doxygen/3.2/imgutils_8c_source.html

ocrmypdf generate supports very large images in most cases, but apparently --clean does not.

In a future release, ocrmypdf should issue a warning or error when --clean is used on images exceeding 256 Mpixels.

**Comment by bennetrr** [comment]
Thanks for the quick response!
When turning of `--clean` it works.
