### ISSUE TITLE
Immediate crash with `ValueError: arguments` on a specific pdf file

### ISSUE THREAD

**Issue by jsgf** [ocrmypdf/OCRmyPDF#902]
**Describe the bug**
ocrmypdf immediately crashes with a ValueError exception on a particular input pdf file.

**To Reproduce**

```bash
$ ocrmypdf -v1 070-4641-00.pdf out.pdf
ocrmypdf 12.7.2
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages (1):
eng

Running: ['tesseract', '--version']
Found tesseract 4.1.3
Running: ['gs', '--version']
Found gs 9.55.0
os.symlink(070-4641-00.pdf, /tmp/ocrmypdf.io.asyf7knk/origin)
os.symlink(/tmp/ocrmypdf.io.asyf7knk/origin, /tmp/ocrmypdf.io.asyf7knk/origin.pdf)
Scanning contents:  33%|██████████████▋                             | 4/12 [00:00<00:00, 25.11page/s]
An exception occurred while executing the pipeline
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 636, in _pdf_pageinfo_sync
    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 714, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 760, in _gather_pageinfo
    for ci in _process_content_streams(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 556, in _process_content_streams
    contentsinfo = _interpret_contents(container, initial_shorthand)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 208, in _interpret_contents
    ctm = PdfMatrix(operands) @ ctm
  File "/usr/lib64/python3.10/site-packages/pikepdf/models/matrix.py", line 55, in __init__
    raise ValueError('arguments')
ValueError: arguments
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 360, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 157, in get_pdfinfo
    return PdfInfo(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 902, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/pdfinfo/info.py", line 679, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 134, in _execute
    for result in results:
  File "/usr/lib64/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
ValueError: arguments

```

**Example file**
https://w140.com/tekwiki/images/8/82/070-4641-00.pdf

**Expected behavior**
Output pdf with ocr

**System**
 - OS: Linux (Fedora 35)
 - OCRmyPDF Version: 12.7.2
 - Installed from disto with `dnf install ocrmypdf`

**Comment by jbarlow83** [comment]
The file contains the following command as part of its content stream for page 5:
```
1.00000 0.00113 -0.00113 1.00000 0.-445 791.310 cm
```

Obviously `0.-445` is not a valid number. Our parser fails at this point.

I suggest using a tool like QPDF to edit the file and manually correct this error or some other program to remove page 5 entirely. ocrmypdf doesn't need to be robust against such an unusual input. This could even be bit rot from a failing storage device. The original file appears to be from 2001.

This PDF's producer describes itself as `Adobe Acrobat Messenger 1.0.1 (<BUILD_DATE>)`. The `<BUILD_DATE>` part is literally included. Doesn't exactly inspire confidence in the original software ;).

Behavior is the same with latest ocrmypdf and pikepdf.

**Comment by jbarlow83** [comment]
Thanks for the report and test file. It was interesting to look at.

**Comment by jbarlow83** [comment]
Closing for now, although if you have other files with this problem (e.g. if it seems a particular program is responsible for producing them) and we can consistently recover the corrupted value, that would make a case for repairing when we detect them.

**Comment by jsgf** [comment]
Thanks for the qpdf suggestion. I changed it to -0.445 and it still renders OK and ocrmypdf is now happy with it.
