### ISSUE TITLE
concurrent.futures.process._RemoteTraceback / encoder error -2 when writing image file with JPEGs

### ISSUE THREAD

**Issue by homocomputeris** [ocrmypdf/OCRmyPDF#905]
**Describe the bug**
```shell
ocrmypdf --force-ocr --lang jpn+jpn_vert+eng 01.pdf 01.pdf
Scanning contents: 100%|████████████████████████████████████████████████| 2/2 [00:00<00:00, 451.70page/s]
Start processing 2 pages concurrently
OCR:   0%|                                                                   | 0.0/2.0 [00:00<?, ?page/s]I/O suspension not supported in scan optimization
OCR:   0%|                                                                   | 0.0/2.0 [00:00<?, ?page/s]
An exception occurred while executing the pipeline
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 202, in exec_page_sync
    visible_image_out = create_visible_page_jpg(visible_image_out, page_context)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 588, in create_visible_page_jpg
    im.save(output_file, format='JPEG', dpi=dpi.to_int())
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 783, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/usr/lib/python3.10/site-packages/PIL/ImageFile.py", line 529, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
OSError: encoder error -2 when writing image file
```

**To Reproduce**
1. Take any image, e.g. https://upload.wikimedia.org/wikipedia/commons/0/00/Old-book-scanned.jpg and save as `test.jpg`
2. `img2pdf *.jpg -o test.pdf`
3. `ocrmypdf --force-ocr --lang jpn+jpn_vert+eng test.pdf test.pdf`
4. Observe the error.

Compare with:
1. `convert test.jpg test.png`
2. `img2pdf *.png -o 01.pdf`
3. `ocrmypdf --force-ocr --lang jpn+jpn_vert+eng 01.png 01.pdf`
which gives rubbish but no error like above (on some random PDFs I also tried, it just worked without any error):
```shell
ocrmypdf --force-ocr --lang jpn+jpn_vert+eng 01.pdf 01.pdf
Scanning contents: 100%|███████████████████████| 1/1 [00:00<00:00, 334.45page/s]
    1 [tesseract] lots of diacritics - possibly poor OCR                        
OCR: 100%|██████████████████████████████████| 1.0/1.0 [00:25<00:00, 25.29s/page]
Postprocessing...
PDF/A conversion: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.79s/page]
GPL Ghostscript 9.55.0 (2021-09-27)
Copyright (C) 2021 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1

   
 Error: File has insufficient data for an image.
               Output may be incorrect.
```

**Expected behavior**
OCR and output a pdf.

**Screenshots**

**System (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.10.2
 - OCRmyPDF version: 13.3.0

**Installation**
From here https://aur.archlinux.org/packages/ocrmypdf/

**Additional context**
Maybe #880

**Comment by homocomputeris** [comment]
Well, it seems that I've confused `--force-ocr` with `--redo-ocr` but that error doesn't seem to be normal behavious, does it?

**Comment by jbarlow83** [comment]
Can't reproduce using your image - please provide the PDF since it looks like img2pdf may be producing an invalid file.

**Comment by homocomputeris** [comment]
Sure.
[test.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7982398/test.pdf)
[01.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/7982397/01.pdf)

Still fails for me.
```shell
ocrmypdf --force-ocr test.pdf test.pdf
Scanning contents: 100%|███████████████████████| 1/1 [00:00<00:00, 351.99page/s]
OCR:   0%|                                          | 0.0/1.0 [00:00<?, ?page/s]I/O suspension not supported in scan optimization
OCR:   0%|                                          | 0.0/1.0 [00:13<?, ?page/s]
An exception occurred while executing the pipeline
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 202, in exec_page_sync
    visible_image_out = create_visible_page_jpg(visible_image_out, page_context)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_pipeline.py", line 588, in create_visible_page_jpg
    im.save(output_file, format='JPEG', dpi=dpi.to_int())
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 783, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "/usr/lib/python3.10/site-packages/PIL/ImageFile.py", line 529, in _save
    raise OSError(f"encoder error {s} when writing image file")
OSError: encoder error -2 when writing image file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
OSError: encoder error -2 when writing image file
ocrmypdf --force-ocr test.pdf test.pdf  13,99s user 0,26s system 100% cpu 14,167 total
```

**Comment by jbarlow83** [comment]
Not reproducible with test.pdf or 01.pdf. 

I tried:
- ocrmypdf 13.4.0
- img2pdf 0.4.3
- Ghostscript 9.55.0 (using Artifex static binary) and 9.54 (system)
- Pillow 9.0.2
- Python 3.9 and 3.10
- Python 3.10

Note Pillow changed the underlying jpeg library in Python wheels v9.0.0 to libjpeg-turbo. This could certainly cause things that previously encoded correctly to fail to encode.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html

If you're comforting poking around in the code, perhaps you can set a breakpoint on _pipeline.py line 588 and see if there is anything special about this image right before it is saved, if you can save it with other settings, (can you save it as a PNG? JPEG without `dpi=`?).


>Still fails for me.

Just in case - the reason it's mentioned that reproducing fails is not to dispute the veracity of your issue; it's to indicate that work was attempted and that more information is needed to isolate the test failure.

**Comment by jbarlow83** [comment]
Closing this as a fixed-upstream third-party bug.

The crash is the Pillow/libjpeg-turbo **"I/O suspension not supported in scan optimization"** issue (`encoder error -2`), which was introduced when Pillow 9.0.0 switched its binary wheels to libjpeg-turbo in early 2022 — exactly when this was reported (v13.3.0, Pillow 9.0.x). It surfaced in OCRmyPDF when saving the visible-page JPEG.

It is no longer reproducible on current software:

- Both `test.pdf` and `01.pdf` run cleanly through `--force-ocr` on the current OCRmyPDF (the DCTDecode image does take the JPEG save path).
- Even forcing the exact failure condition — `ImageFile.MAXBLOCK = 100` on a 4000×2500 high-entropy RGB image — Pillow 12.2.0 / libjpeg-turbo 3.1.4 encodes without error. The upstream suspension-handling bug is fixed.

(For the record, the `--force-ocr` vs `--redo-ocr` mix-up noted above was incidental — the error was in the rasterize→JPEG path common to both, not related to the OCR mode.)

If anyone hits an `encoder error -2` again on a current Pillow, please open a fresh issue with the input file and your Pillow/libjpeg-turbo versions (`python -c "import PIL, PIL.features; print(PIL.__version__, PIL.features.version('libjpeg_turbo'))"`).
