### ISSUE TITLE
Ocrmypdf crashes

### ISSUE THREAD

**Issue by All3xJ** [ocrmypdf/OCRmyPDF#917]
**Describe the bug**
crashes if I open it

**To Reproduce**
just write ocrmypdf in a terminal

**Expected behavior**
should not crash

**Screenshots**
```
$ ocrmypdf --help
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 33, in <module>
    sys.exit(load_entry_point('ocrmypdf==13.3.0', 'console_scripts', 'ocrmypdf')())
  File "/usr/lib/python3.10/site-packages/ocrmypdf/__main__.py", line 35, in run
    _parser, options, plugin_manager = get_parser_options_plugins(args=args)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 116, in get_parser_options_plugins
    plugin_manager = get_plugin_manager(pre_options.plugins)
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 104, in get_plugin_manager
    pm = OcrmypdfPluginManager(
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 45, in __init__
    self.setup_plugins()
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_plugin_manager.py", line 73, in setup_plugins
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 11, in <module>
    from ocrmypdf._exec import ghostscript
  File "/usr/lib/python3.10/site-packages/ocrmypdf/_exec/ghostscript.py", line 21, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/home/allexj/.local/lib/python3.10/site-packages/PIL/__init__.py)
```

**System (please complete the following information):**
 - OS: Archlinux
 - Python version: 3.10
 - OCRmyPDF version: 13.3.0-1

**Installation**
How did you install OCRmyPDF? Did you install it from your operating system's
package manager, or using pip?
I installed it via AUR

**Additional context**

**Comment by jbarlow83** [comment]
Please report this to AUR as it is like a packaging issue. Specifically you may have an older version of Pillow, or perhaps a new version with breaking changes.

**Comment by jbarlow83** [comment]
Closed due to likely third party issue and inactivity
