### ISSUE TITLE
Error processing a list of pdf

### ISSUE THREAD

**Issue by marcorighi** [ocrmypdf/OCRmyPDF#919]
**Describe the bug**
Sometimes ocrmypdf freezes

**To Reproduce**
I wrote a script to process a list of PDFs. During the processing, randomly, the script freezes. It happens with several hundred PDFs to process.

Here is a typical out with freezing. 

```
(Tot to process 315 - Wed Feb 16 12:07:52 CET 2022) processing sivasutra.pdf    
Scanning contents: 100%|███████████████████| 115/115 [00:00<00:00, 735.13page/s]
Start processing 16 pages concurrently                                          
OCR:   0%|                                        | 0.0/115.0 [00:00<?, ?page/s]
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force 
OCR;  see also help for the arguments --skip-text and --redo-ocr                
(Tot to process 314 - Wed Feb 16 12:07:53 CET 2022) processing S.L.JJ_Smith_Tab.pdf                                                              
Scanning contents: 100%|█████████████████████| 23/23 [00:00<00:00, 102.73page/s]
Start processing 16 pages concurrently                                          
OCR:   0%|                                         | 0.0/23.0 [00:00<?, ?page/s]
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force 
OCR;  see also help for the arguments --skip-text and --redo-ocr                
(Tot to process 313 - Wed Feb 16 12:07:54 CET 2022) processing Brown_Kull_T_The_
Use_and_Joy_of_eggs_2022.pdf                                           
Scanning contents: 100%|██████████████████| 221/221 [00:00<00:00, 1310.60page/s]
Start processing 16 pages concurrently                                          
OCR:   0%|                                        | 0.0/221.0 [00:00<?, ?page/s]
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force 
OCR;  see also help for the arguments --skip-text and --redo-ocr  
```

The only solution is CTRL-C to interrupt the process, move the files already processed and start again.

Follows the bash script

```
#!/bin/bash
if [ "$1" = "" ]; then
echo "esempio: $0 [-force] [-lENG] *pdf"
exit 0;
fi 

FORCE=false
LANG=ita

str=$1;
#echo "+${str:0:1}+"
while [ "${str:0:1}" == "-" ]; do
    #echo "PARAMETRO"
    #echo "*${str:0:1}*" 
    #echo "*$str*"
    #echo "+++"
    if [ "$str" == "-force" ]; then
        FORCE=true
        shift;
    fi
    if [ "${str:0:2}" == "-l" ]; then
        LANG=$(echo ${str:2})
        shift;
    fi 
str=$1;    
done;

if [ $FORCE = true ]; then 
    echo "FORCE ON"
else
    echo "FORCE OFF"
fi
echo "LANGUAGE $LANG"
while [ -n "$1" ]
do
  if [ "$1" != "" ]; then
    #filename=$(basename -- "$1")
    filename="${1%.*}"
    extension="${1##*.}"
    echo "(Tot to process $# - $(date)) processing $1"
    if [ $FORCE = true ]
    then
                #echo "FORCE ++++++++++++++++++++++++++++++++"
                ocrmypdf --force -l${LANG} "$1" "$filename.ocr.$extension"
    else
                #echo "FORCE --------------------------------"
                ocrmypdf -l${LANG} "$1" "$filename.ocr.$extension"
        fi
        if [ ! -f "$filename.ocr.$extension" ]; then
        mv "$1" "$filename.previous.ocr.$extension"
        fi
  fi
  shift;
done
```

Using  `-v1` the last output (on a different example) before the freezing is

```
[previous output omitted]

  File "/usr/lib/python3.10/site-packages/ocrmypdf/_concurrent.py", line 82, in 
__call__                                                                        
    self._execute(                                                              
  File "/usr/lib/python3.10/site-packages/ocrmypdf/builtin_plugins/concurrency.p
y", line 135, in _execute                                                       
    result = future.result()                                                    
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result   
    return self.__get_result()                                                  
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_res
ult                                                                             
    raise self._exception                                                       
ocrmypdf.exceptions.PriorOcrFoundError: page already has text! - aborting (use -
-force-ocr to force OCR;  see also help for the arguments --skip-text and --redo
-ocr                                                                            
   32 Running: ['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpola
teControl=-1', '-sDEVICE=pngmono', '-dFirstPage=32', '-dLastPage=32', '-r600.000
001x600.000001', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f',
 '/tmp/ocrmypdf.io.1rmr1nol/origin.pdf']                                        
```

**Example file**
If your issue is a problem that affects only certain files, and we will require an input file (PDF or image) that demonstrates your issue.

Please provide an input file with no personal or confidential information. At your option you may [GPG-encrypt the file](https://github.com/jbarlow83/OCRmyPDF/wiki) for OCRmyPDF's author only.

Links to files hosted elsewhere are perfectly acceptable. You could also look in ``tests/resources`` and see if any of those files reproduce your issue.

*(Issues without example files usually cannot be resolved. It's like reporting an issue against a web browser without providing a URL.)*

**Expected behavior**
I expect to obtain files with ocr ending with .ocr.pdf extension.

**System**
 - OS: 
lsb_release -a                                               |

LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.2.3
Codename:       Qonos

 - OCRmyPDF Version:
ocrmypdf --version

13.3.0
 
 - How did you install ocrmypdf? 
yay -Suuyy
yay -S ocrmypdf
(AUR repository)

**Comment by marcorighi** [comment]
I am going to add some information. 

After that ocrmypdf freezes the previous script, by pressing CTRL-C we got


```
PriorOcrFoundError: page already has text! - aborting (use --force-ocr to force 
OCR;  see also help for the arguments --skip-text and --redo-ocr                
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.
py'>                                                                            
Traceback (most recent call last):                                              
  File "/usr/lib/python3.10/threading.py", line 1530, in _shutdown              
    atexit_call()                                                               
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 95, in _python_
exit                                                                            
    t.join()
  File "/usr/lib/python3.10/threading.py", line 1089, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1109, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt: 
```
by pressing again CTRL-C the script processes the next file. 

The freezing is typical ol already OCR pdf files.

**Comment by jbarlow83** [comment]
Same as #814
