### ISSUE TITLE
 invalid int value

### ISSUE THREAD

**Issue by aliafshany** [ocrmypdf/OCRmyPDF#927]
**Describe the bug**
i can not use ocrmypdf, i tried verbose mode and this is my error:
ocrmypdf: error: argument -v/--verbose: invalid int value: 'new.pdf'
it seems strange, i was working with it untill a few days ago

```bash
ocrmypdf -l fas -c -f -v1 new.pdf  2.pdf

Run with verbosity or higher `-v1` to see more detailed logging. This information may be helpful.
`ocrmypdf 13.4.0
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages in "/usr/local/share/tessdata/" (163):
afr
amh
ara
asm
aze
aze_cyrl
bel
ben
bod
bos
bre
bul
cat
ceb
ces
chi_sim
chi_sim_vert
chi_tra
chi_tra_vert
chr
cos
cym
dan
deu
div
dzo
ell
eng
enm
epo
equ
est
eus
fao
fas
fil
fin
fra
frk
frm
fry
gla
gle
glg
grc
guj
hat
heb
hin
hrv
hun
hye
iku
ind
isl
ita
ita_old
jav
jpn
jpn_vert
kan
kat
kat_old
kaz
khm
kir
kmr
kor
kor_vert
lao
lat
lav
lit
ltz
mal
mar
mkd
mlt
mon
mri
msa
mya
nep
nld
nor
oci
ori
osd
pan
pol
por
pus
que
ron
rus
san
script/Arabic
script/Armenian
script/Bengali
script/Canadian_Aboriginal
script/Cherokee
script/Cyrillic
script/Devanagari
script/Ethiopic
script/Fraktur
script/Georgian
script/Greek
script/Gujarati
script/Gurmukhi
script/HanS
script/HanS_vert
script/HanT
script/HanT_vert
script/Hangul
script/Hangul_vert
script/Hebrew
script/Japanese
script/Japanese_vert
script/Kannada
script/Khmer
script/Lao
script/Latin
script/Malayalam
script/Myanmar
script/Oriya
script/Sinhala
script/Syriac
script/Tamil
script/Telugu
script/Thaana
script/Thai
script/Tibetan
script/Vietnamese
sin
slk
slv
snd
snum
spa
spa_old
sqi
srp
srp_latn
sun
swa
swe
syr
tam
tat
tel
tgk
tha
tir
ton
tur
uig
ukr
urd
uzb
uzb_cyrl
vie
yid
yor

Running: ['unpaper', '--version']
Found unpaper 6.1
Running: ['tesseract', '--version']
Found tesseract 5.1.0
Running: ['gs', '--version']
Found gs 9.55.0
os.symlink(new.pdf, /var/folders/2x/0gcwtlsj6zn1p9fp5z6lqf400000gn/T/ocrmypdf.io.1awqq9e6/origin)
Temporary file was at: /var/folders/2x/0gcwtlsj6zn1p9fp5z6lqf400000gn/T/ocrmypdf.io.1awqq9e6/origin
ExitCodeException
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/13.4.0/libexec/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 128, in triage
    if _pdf_guess_version(input_file):
  File "/usr/local/Cellar/ocrmypdf/13.4.0/libexec/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 118, in _pdf_guess_version
    with open(input_file, 'rb') as f:
PermissionError: [Errno 1] Operation not permitted: '/var/folders/2x/0gcwtlsj6zn1p9fp5z6lqf400000gn/T/ocrmypdf.io.1awqq9e6/origin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/13.4.0/libexec/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 365, in run_pipeline
    origin_pdf = triage(
  File "/usr/local/Cellar/ocrmypdf/13.4.0/libexec/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 140, in triage
    raise InputFileError(msg) from e
ocrmypdf.exceptions.InputFileError: [Errno 1] Operation not permitted: 'new.pdf'`
**Example file**
If your issue is a problem that affects only certain files, and we will require an input file (PDF or image) that demonstrates your issue.

Please provide an input file with no personal or confidential information. At your option you may [GPG-encrypt the file](https://github.com/jbarlow83/OCRmyPDF/wiki) for OCRmyPDF's author only.

Links to files hosted elsewhere are perfectly acceptable. You could also look in ``tests/resources`` and see if any of those files reproduce your issue.

*(Issues without example files usually cannot be resolved. It's like reporting an issue against a web browser without providing a URL.)*

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
https://user-images.githubusercontent.com/40741745/156781667-24e101bd-c142-4d79-9965-28b4a10f6ec0.png
**System**
 - OS: macos 11.6.2
 - OCRmyPDF Version: 13.4.0
 - How did you install ocrmypdf? Did you use a system package manager, `pip`, or a Docker image? homebrew

**Comment by aliafshany** [comment]
it was my mac problem not from your end.
sorry

solved by this tutorial: https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
