### ISSUE TITLE
"remove-background not implemented"

### ISSUE THREAD

**Issue by bouboulov** [ocrmypdf/OCRmyPDF#944]
**Describe the bug**
Apparently i have some trouble with the remove-background option

**Screenshots**
```
Scanning contents: 100%|███████████████████| 412/412 [00:00<00:00, 528.17page/s]
Start processing 4 pages concurrently
OCR:   0%|                                        | 0.0/412.0 [00:05<?, ?page/s]
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_sync.py", line 192, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_sync.py", line 135, in make_intermediate_images
    preprocess_out = preprocess(
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_sync.py", line 104, in preprocess
    image = preprocess_remove_background(image, page_context)
  File "/home/bouboulov/.venv/lib64/python3.9/site-packages/ocrmypdf/_pipeline.py", line 476, in preprocess_remove_background
    raise NotImplementedError("--remove-background is temporarily not implemented")
NotImplementedError: --remove-background is temporarily not implemented

```

**System (please complete the following information):**
 - OS: Slackware 15 / venv
 - Python version: Python 3.9.12
 - OCRmyPDF version: ocrmypdf 13.4.2

**Installation**
using pip in virtual env

**Comment by jbarlow83** [comment]
The feature was removed (due to stability difficulties with the underlying library) and has not been re-implemented in a way that is independent of that library. Originally I was hoping to restore it quickly after the v13 release but that didn't happen.

If you really need the feature, downgrade to v12 (but... stability may be an issue).

**Comment by bouboulov** [comment]
Thanks for the fast reply ! 

Have a nice day :)

**Comment by PaulWoitaschek** [comment]
If this is only temporarily removed, what about reopening this issue until it's been put back?

**Comment by bouboulov** [comment]
I didn't try new versions since then, I just reinstalled it but the remove background is not implemented yet. I think the guys at Debian managed to keep it somehow, it could be useful to see what they've done.  I'll let jbarlow83 decide as I'm pretty sure it's a leptonica issue.

**Comment by jbarlow83** [comment]
I do appreciate this has been frustrating and the "temporary" removal has gone on longer than I'd have liked. 

Most likely remove background will be reintroduced as a plugin (because it requires several additional libraries, specifically scikit-image, scipy, numpy) and will use the rolling ball method.

I'm not going to return to binding leptonica.

**Comment by PaulWoitaschek** [comment]
Great, I'm looking forward to it!

I'm using this library transitively with paperless-ngx and it's so much better sharing non grey pdfs
