### ISSUE TITLE
ERROR - Ghostscript rasterizing failed for Some PDFs

### ISSUE THREAD

**Issue by upuldi** [ocrmypdf/OCRmyPDF#952]
[2022-05-04 11:19:39,039] [ERROR] [paperless.consumer] Error while consuming document 220407-Concept_01(XXXXXXXXX.pdf) (4).pdf: SubprocessOutputError: Ghostscript rasterizing failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 126, in rasterize_pdf

    p = run(args_gs, stdout=PIPE, stderr=PIPE, check=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 53, in run

    proc = subprocess_run(args, env=env, **kwargs)

  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['gs', '-dQUIET', '-dSAFER', '-dBATCH', '-dNOPAUSE', '-dInterpolateControl=-1', '-sDEVICE=jpeggray', '-dFirstPage=2', '-dLastPage=2', '-r10613.793103x10613.793103', '-o', '-', '-sstdout=%stderr', '-dAutoRotatePages=/None', '-f', '/tmp/ocrmypdf.io.5aaq4owc/origin.pdf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 261, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline

    exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync

    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 344, in rasterize_preview

    page_context.plugin_manager.hook.rasterize_pdf_page(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__

    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall

    return outcome.get_result()

  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page

    ghostscript.rasterize_pdf(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf

    raise SubprocessOutputError('Ghostscript rasterizing failed')

ocrmypdf.exceptions.SubprocessOutputError: Ghostscript rasterizing failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 261, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 314, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: SubprocessOutputError: Ghostscript rasterizing failed

**Comment by jbarlow83** [comment]
This cannot be investigated without a test file and all of the other information required in the issue template.

**Comment by salexan2001** [comment]
I experienced a similar problem with a pdf file:
```
InputFileError: Ghostscript rasterizing failed. The input file contains errors _common.py:273
that cause PDF viewers to interpret it differently and incorrectly. Try using                
--continue-on-soft-render-error and manually inspect the input and output                    
files to check for visual differences or errors.
```

I just wanted to share my workaround here:
I converted the pdf using ImageMagick/convert (`convert -density 210 input.pdf output.pdf`) and ran `ocrmypdf` on `output.pdf`.

```bash
$ ocrmypdf --version
16.10.2
```

**Comment by jbarlow83** [comment]
@salexan2001 You would still need to confirm that the PDF is not visually altered by running that tool.
