### ISSUE TITLE
AttributeError: 'pikepdf._qpdf.Pdf' object has no attribute 'root'

### ISSUE THREAD

**Issue by some1ataplace** [ocrmypdf/OCRmyPDF#957]
ocrmypdf in.pdf out.pdf

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 353, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 164, in get_pdfinfo
    return PdfInfo(
  File "/usr/lib/python3/dist-packages/ocrmypdf/pdfinfo/info.py", line 821, in __init__
    self._needs_rendering = pdf.root.get('/NeedsRendering', False)
AttributeError: 'pikepdf._qpdf.Pdf' object has no attribute 'root'

Solved it by running:
```
sudo apt remove ocrmypdf
pip3 install ocrmypdf
sudo apt install ocrmypdf
ocrmypdf in.pdf out.pdf
```

**Comment by jbarlow83** [comment]
Missing ocrmypdf version and other information needed to investigate.
