### ISSUE TITLE
Docker Image Issue - RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Zaxim** [ocrmypdf/OCRmyPDF#968]
**Describe the bug**
Docker container cannot start using v13.4.4 image. It gives me the following error.

```
ocrmypdf     | RuntimeError: can't start new thread
ocrmypdf     | Starting OCRmyPDF watcher with config:
ocrmypdf     | Input Directory: /input
ocrmypdf     | Output Directory: /output
ocrmypdf     | Output Directory Year & Month: False
ocrmypdf     | INPUT_DIRECTORY: /input
ocrmypdf     | OUTPUT_DIRECTORY: /output
ocrmypdf     | OUTPUT_DIRECTORY_YEAR_MONTH: False
ocrmypdf     | ON_SUCCESS_DELETE: True
ocrmypdf     | DESKEW: True
ocrmypdf     | ARGS: {'rotate_pages': True, 'rotate_pages_threshold': 4.0}
ocrmypdf     | POLL_NEW_FILE_SECONDS: 1
ocrmypdf     | USE_POLLING: False
ocrmypdf     | LOGLEVEL: DEBUG
ocrmypdf     | Traceback (most recent call last):
ocrmypdf     |   File "/app/watcher.py", line 172, in <module>
ocrmypdf     |     main()
ocrmypdf     |   File "/app/watcher.py", line 162, in main
ocrmypdf     |     observer.start()
ocrmypdf     |   File "/usr/local/lib/python3.10/dist-packages/watchdog/observers/api.py", line 262, in start
ocrmypdf     |     emitter.start()
ocrmypdf     |   File "/usr/local/lib/python3.10/dist-packages/watchdog/utils/__init__.py", line 93, in start
ocrmypdf     |     self.on_thread_start()
ocrmypdf     |   File "/usr/local/lib/python3.10/dist-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
ocrmypdf     |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
ocrmypdf     |   File "/usr/local/lib/python3.10/dist-packages/watchdog/observers/inotify_buffer.py", line 36, in __init__
ocrmypdf     |     self.start()
ocrmypdf     |   File "/usr/local/lib/python3.10/dist-packages/watchdog/utils/__init__.py", line 94, in start
ocrmypdf     |     threading.Thread.start(self)
ocrmypdf     |   File "/usr/lib/python3.10/threading.py", line 928, in start
ocrmypdf     |     _start_new_thread(self._bootstrap, ())
ocrmypdf     | RuntimeError: can't start new thread
```

**To Reproduce**
Set docker-compose image to `jbarlow83/ocrmypdf:v13.4.4`

**Expected behavior**
The container would start and watcher.py would process PDF files

**System (please complete the following information):**
Docker image running via docker-compose  on`docker version 20.10.5, build 55c4c88`

Host machine
```
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.101-1-pve
      Architecture: x86-64
```

**Additional context**
Downgrading to `jbarlow83/ocrmypdf:v13.4.3` allows the container to start nomrally

**Comment by Zaxim** [comment]
Upgraded to `Docker version 20.10.17, build 100c701`
Upgraded my host
```
Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.189-1-pve
      Architecture: x86-64
```
And gave it a nice reboot and everything is working fine on `latest`
