### ISSUE TITLE
[LIBRARY BUG] Requirement.parse('cryptography~=36.0.0')

### ISSUE THREAD

**Issue by marcorighi** [ocrmypdf/OCRmyPDF#969]
**Describe the bug**
Bug after update on Manjaro Linux

**To Reproduce**
Just perform an ocr of  a PDF

**Expected behavior**
to get a PDF whiteout error

**Screenshots**
`ocrmypdf test.pdf 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 37.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cryptography~=36.0.0'), {'pdfminer.six'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 33, in <module>
    sys.exit(load_entry_point('ocrmypdf==13.4.4', 'console_scripts', 'ocrmypdf')())
  File "/usr/bin/ocrmypdf", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ocrmypdf/__init__.py", line 10, in <module>
    from ocrmypdf import helpers, hocrtransform, pdfa, pdfinfo
  File "/usr/lib/python3.10/site-packages/ocrmypdf/helpers.py", line 22, in <module>
    import img2pdf
  File "/usr/lib/python3.10/site-packages/img2pdf.py", line 59, in <module>
    import pikepdf
  File "/usr/lib/python3.10/site-packages/pikepdf/__init__.py", line 19, in <module>
    from ._version import __version__
  File "/usr/lib/python3.10/site-packages/pikepdf/_version.py", line 7, in <module>
    from pkg_resources import DistributionNotFound
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3317, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3291, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3329, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography~=36.0.0' distribution was not found and is required by pdfminer.six
`

**System (please complete the following information):**
 - OS:
`
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.2.6
Codename:	Qonos
`
 - Python version:
`
python --version
Python 3.10.4
`
 - OCRmyPDF version:
`
yay -Ss ocr|grep mypdf
aur/ocrmypdf 13.4.4-1 (+70 2.22)
`

**Installation**
pamac build (yay has some error on colordialogs)

**Additional context**
Problem signaled on AUR

**Comment by marcorighi** [comment]
Sorry to insist. The error is

`pkg_resources.ContextualVersionConflict: (cryptography 37.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cryptography~=36.0.0'), {'pdfminer.six'})`

It seems to me that the AUR's problem (the problem afflicts Arch Linux too) concerns the fact that  AUR has installed a new version of the  cryptography library but  `ocrmypdf` is still referring to an old one. Isn't it? Can `ocrmypdf` use the new version of cryptography?

Thx

**Comment by jbarlow83** [comment]
ocrmypdf does not list cryptography as a dependency at all. pdfminer.six does, so it looks like AUR has the dependency pinned to an older version.

**Comment by musicinmybrain** [comment]
This was caused by pdfminer.six 20220526 [pinning cryptography](https://github.com/pdfminer/pdfminer.six/commit/1bf3c42b59125f4491d863e1c11dca7ebbe96adc#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R20). The pin was [removed](https://github.com/pdfminer/pdfminer.six/pull/755) in [20220524](https://github.com/pdfminer/pdfminer.six/releases/tag/20220524)—but now OCRmyPDF needs to [allow that version](https://github.com/ocrmypdf/OCRmyPDF/issues/970).

**Comment by xversion1** [comment]
I don't know why this issue hasn't been fixed on my computer. I still get this error when I try to use ocrmypdf. Need to mention that my other computer with (almost) the same system (Arch Linux) doesn't have this problem. Both are the latest version.

**Comment by jbarlow83** [comment]
```
pkg_resources.ContextualVersionConflict: (cryptography 37.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cryptography~=36.0.0'), {'pdfminer.six'})
```

It's clearly saying that there's an older pdfminer.six that needs 36.0.

**Comment by xversion1** [comment]
> 

Is there a way I can install cryptography 36.0 while keeping 37.0?

**Comment by jbarlow83** [comment]
You can create a Python virtual environment and install ocrmypdf there.
