### ISSUE TITLE
subprocess.CalledProcessError: Command '['tesseract'...] died with <Signals.SIGKILL: 9>.

### ISSUE THREAD

**Issue by browntownington** [ocrmypdf/OCRmyPDF#976]
**Describe the bug**
Firstly I am new to ocrmypdf.
I have  several large documents (40 pages, 60 pages)  scanned at 600 dpi. When I attempt to OCR with ocrmypdf the process crashes with: 

`subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.bp9m25sm/000006_ocr.png', '/tmp/ocrmypdf.io.bp9m25sm/000006_ocr_tess', 'pdf', 'txt']' died with <Signals.SIGKILL: 9>.`

The same documents scanned at 300dpi ocr successfully.

I ran a verbose debug (level 2) and noted that the process crashed on page 16. So I ran a ocrmypdf on the same 600dpi document and only specified to ocr page 16 and the process ran successfully. So page 16 itself isn't an issue.

The same subprocess that is crashing seems to run successfully with previous pages. Suspect maybe this has something to do with system resources?

**To Reproduce**
ocrmypdf input.pdf output.pdf

**Expected behavior**
To successfully OCR the whole PDF without crashing.

**Screenshots**
```
  DEBUG PIL.PngImagePlugin -   16  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -   16  STREAM b'iCCP' 41 2354
  DEBUG PIL.PngImagePlugin -   16  iCCP profile name b'default_rgb.icc'
  DEBUG PIL.PngImagePlugin -   16  Compression method 0
  DEBUG PIL.PngImagePlugin -   16  STREAM b'pHYs' 2407 9
  DEBUG PIL.PngImagePlugin -   16  STREAM b'tEXt' 2428 31
  DEBUG PIL.PngImagePlugin -   16  STREAM b'IDAT' 2471 8192
  DEBUG ocrmypdf._exec.ghostscript -   16  Rotating output by 0
WARNING ocrmypdf._exec.tesseract -   13  [tesseract] lots of diacritics - possibly poor OCR
  DEBUG ocrmypdf.subprocess -   15  Running: ['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.bp9m25sm/000015_ocr.png', '/tmp/ocrmypdf.io.bp9m25sm/000015_ocr_tess', 'pdf', 'txt']
  DEBUG PIL.PngImagePlugin -   16  STREAM b'IHDR' 16 13
  DEBUG PIL.PngImagePlugin -   16  STREAM b'iCCP' 41 2350
  DEBUG PIL.PngImagePlugin -   16  iCCP profile name b'ICC Profile'
  DEBUG PIL.PngImagePlugin -   16  Compression method 0
  DEBUG PIL.PngImagePlugin -   16  STREAM b'pHYs' 2403 9
  DEBUG PIL.PngImagePlugin -   16  STREAM b'IDAT' 2424 65536
  DEBUG ocrmypdf._pipeline -   16  resolution (599.9988, 599.9988)
  DEBUG ocrmypdf.subprocess -   16  Running: ['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.bp9m25sm/000016_ocr.png', '/tmp/ocrmypdf.io.bp9m25sm/000016_ocr_tess', 'pdf', 'txt']
  ERROR ocrmypdf._sync - ExitCodeException
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_exec/tesseract.py", line 410, in generate_pdf
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/subprocess/__init__.py", line 53, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '-c', 'textonly_pdf=1', '/tmp/ocrmypdf.io.bp9m25sm/000006_ocr.png', '/tmp/ocrmypdf.io.bp9m25sm/000006_ocr_tess', 'pdf', 'txt']' died with <Signals.SIGKILL: 9>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__
    self._execute(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_sync.py", line 216, in exec_page_sync
    (ocr_out, text_out) = ocr_engine_textonly_pdf(ocr_image_out, page_context)
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_pipeline.py", line 658, in ocr_engine_textonly_pdf
    ocr_engine.generate_pdf(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 192, in generate_pdf
    tesseract.generate_pdf(
  File "/usr/local/lib/python3.10/dist-packages/ocrmypdf/_exec/tesseract.py", line 422, in generate_pdf
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
```

**System (please complete the following information):**
 - OS: Latest Docker Image
 - Python version: Latest Docker Image
 - OCRmyPDF version: Latest Version in Docker Image

**Installation**
Docker Image

**Additional context**
No

**Comment by jbarlow83** [comment]
SIGKILL on Linux usually means that the out of memory (OOM) killer decided to terminate the process. 

By chance are you running a memory limited environment like a virtual machine?

**Comment by browntownington** [comment]
Okay that makes sense.

It's running on Docker Desktop using WSL2 engine with 4gb memory allocated. I would have assumed 4gb would more than suffice.

I'll allocate 8gb and test again.

**Comment by jbarlow83** [comment]
If you have several CPU cores all working on 600 DPI images (100 MB/page) it's quite possible to hit a 4 GB cap.

**Comment by browntownington** [comment]
Thank you @jbarlow83 good lesson learnt. Watching the resources I noted it peaks to 5.7gb. So after setting memory cap to 6gb managed to resolve this.
